<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/rest/twitter/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_LICENSING_INFO' => '<table border="0" cellspacing="1"><tr><td valign="top" width="35%" class="dataLabel">Sugar kurulumunuzu Twitter&#169; ortamına  yeni bir uygulama olarak kaydederek Müşteri Anahtarı ve Gizli Anahtar alın.<br/><br>Uygulamanızı kaydetmek için gereken adımlar:<br/><br/><ol><li>Twitter&#169; uygulama geliştirme sayfasına gidin: <a href="http://dev.twitter.com/apps/new" target="_blank">http://dev.twitter.com/apps/new</a>.</li><li>Uygulamanızı kaydetmek istediğiniz Twitter&#169; hesabınızla giriş yapın.</li><li>Kayıt formunda uygulama ismini girin. Bu alan kullanıcıların Twitter&#169; hesaplarını Sugar içinde otantike etmek için görecekleri alandır.</li><li>Açıklama girin.</li><li>Uygulama için bir web sitesi adresi girin (herhangi bir adres olabilir).</li><li>Uygulama tipini seçmek için "Browser" seçin.</li><li>Uygulama tipini seçtikten sonra bir tane Geri Dönüş (Callback) URL adresi girin. (herhangi bir adres olabilir. Sugar otantikasyon sırasında bu adresi kullanmayacak). Örneğin: Sugar uygulamasının URL adresi.</li><li>Güvenlik kelimelerinizi girin.</li><li>"Register Application" tıklayın </li><li>Twitter API kullanım şartlarını kabul edin.</li><li>Uygulama sayfasında Müşteri İsmi ve Şifre Anahtarını bulun ve aşağıya girin.</li></ol></td></tr></table>' ,
   'LBL_NAME' => 'Twitter Kullanıcı İsmi' ,
   'LBL_ID' => 'Twitter Kullanıcı İsmi' ,
   'company_url' => 'URL' ,
   'oauth_consumer_key' => 'Müşteri Anahtarı' ,
   'oauth_consumer_secret' => 'Müşteri Şifresi' );

?>
