
<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

require("include/modules.php");
foreach ($beanFiles as $Classname => $filename){ 
    // Find the name of the file generated by the updateclass script
	$pos=strrpos($filename,"/");
	$Newfilename=substr_replace($filename, 'SugarCore.', $pos+1, 0);
    //delete the new SugarBean that extends CoreBean and replace it by the old one undoing all the changes
	if (file_exists($Newfilename)){
		unlink($filename);
		$handle = file_get_contents($Newfilename);
		$data = preg_replace("/class SugarCore".$Classname."/", 'class '.$Classname, $handle);
		$data1 = preg_replace("/function SugarCore".$Classname."/", 'function '.$Classname, $data);
		file_put_contents($Newfilename,$data1);
		rename($Newfilename,$filename);
	}
}
?>
