/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({plugins:['Dropdown','Timeago','EllipsisInline','Tooltip'],collection:null,_alertsCollections:{},_intervals:{},_intervalId:null,_defaultOptions:{delay:5,limit:4,severity_css:{alert:'label-important',information:'label-info',other:'label-inverse',success:'label-success',warning:'label-warning'}},initialize:function(options){options.module='Notifications';this._super('initialize',[options]);app.events.on('app:sync:complete',this._bootstrap,this);app.events.on('app:logout',this.stopPulling,this);},_bootstrap:function(){this._initOptions();this._initCollection();this._initReminders();this.startPulling();return this;},_initOptions:function(){var options=_.extend(this._defaultOptions,this.meta||{});this.delay=options.delay*60*1000;this.limit=options.limit;this.severityCss=options.severity_css;return this;},_initCollection:function(){this.collection=app.data.createBeanCollection(this.module);this.collection.options={params:{order_by:'date_entered:desc'},limit:this.limit,myItems:true,fields:['date_entered','id','name','severity']};this.collection.sync=_.wrap(this.collection.sync,function(sync,method,model,options){options=options||{};options.endpoint=function(method,model,options,callbacks){var url=app.api.buildURL(model.module,'pull',{},options.params);return app.api.call('read',url,{},callbacks);};sync(method,model,options);});return this;},_initReminders:function(){var timeOptions=_.keys(app.lang.getAppListStrings('reminder_time_options')),max=_.max(timeOptions,function(key){return parseInt(key,10);});this.reminderMaxTime=parseInt(max,10)+this.delay / 1000;_.each(['Calls','Meetings'],function(module){this._alertsCollections[module]=app.data.createBeanCollection(module);this._alertsCollections[module].options={limit:this.meta.remindersLimit,fields:['date_start','id','name','reminder_time','location']};this._intervals[module]={};},this);return this;},getSeverityLabel:function(severity){var list=app.lang.getAppListStrings('notifications_severity_list');return list[severity]||severity;},getSeverityCss:function(severity){return this.severityCss[severity]||'';},startPulling:function(){if(!_.isNull(this._intervalId)){return this;}
var self=this;this.pull();this._pullReminders();this._intervalId=window.setInterval(function(){if(!app.api.isAuthenticated()){self.stopPulling();return;}
self.pull();self._pullReminders();},this.delay);return this;},stopPulling:function(){if(!_.isNull(this._intervalId)){window.clearInterval(this._intervalId);this._intervalId=null;}
return this;},pull:function(){if(this.disposed||this.isOpened()){return this;}
var self=this;this.collection.fetch({success:function(){if(self.disposed||self.isOpened()){return this;}
self.render();}});return this;},_pullReminders:function(){if(this.disposed){return this;}
var date=new Date(),startDate=date.toISOString(),endDate;date.setTime(date.getTime()+this.reminderMaxTime*1000);endDate=date.toISOString();_.each(['Calls','Meetings'],function(module){this._alertsCollections[module].filterDef=_.extend({},this.meta.remindersFilterDef||{},{'date_start':{'$dateBetween':[startDate,endDate]},'users.id':{'$equals':app.user.get('id')}});this._alertsCollections[module].fetch({silent:true,merge:true,apiOptions:{skipMetadataHash:true},success:_.bind(function(data){if(!this.disposed){this._parseReminders(data);}},this)});},this);return this;},_parseReminders:function(data){if(!data.length){return this;}
var deadIds=_.difference(_.keys(this._intervals[data.module]),data.pluck('id'));_.each(deadIds,function(id){this._clearReminders(data.module,id);},this);data.each(function(model){this._parseReminder(model);},this);return this;},_parseReminder:function(model){var hasChanged=!_.has(this._intervals[model.module],model.id)||!!model.changedAttributes(this._intervals[model.module][model.id].prevAttr);if(!hasChanged){return this;}
var diff=new Date(model.get('date_start'))-new Date(),delay=diff-parseInt(model.get('reminder_time'),10)*1000;if(delay<0){return this;}
this._clearReminders(model.module,model.id);this._intervals[model.module][model.id]={timer:setTimeout(_.bind(function(){this._showReminderAlert(model);},this),delay),prevAttr:_.pick(model.attributes,'reminder_time','date_start')};return this;},_clearReminders:function(module,id){if(id){if(_.has(this._intervals[module],id)){clearTimeout(this._intervals[module][id].timer);delete this._intervals[module][id];}
return;}
_.each(this._intervals[module],function(data){clearTimeout(data.timer);},this);this._intervals[module]={};},_showReminderAlert:function(model){var url=app.router.buildRoute(model.module,model.id),dateFormat=app.user.getPreference('datepref')+' '+app.user.getPreference('timepref'),dateValue=app.date.format(new Date(model.get('date_start')),dateFormat),template=app.template.getView('notifications.notifications-alert'),message=template({title:app.lang.get('LBL_REMINDER_TITLE',model.module),module:model.module,model:model,location:model.get('location'),description:model.get('description'),dateStart:dateValue});_.defer(function(){if(confirm(message)){app.router.navigate(url,{trigger:true});}});delete this._intervals[model.module][model.id];},isOpened:function(){return this.$('.notification-list').hasClass('open');},_renderHtml:function(){if(!app.api.isAuthenticated()||app.config.appStatus==='offline'){return;}
if(!_.isObject(this.collection)){this._super('_renderHtml');return;}
_.each(this.collection.models,function(model){model.set('severityCss',this.getSeverityCss(model.get('severity')));model.set('severityLabel',this.getSeverityLabel(model.get('severity')));},this);this._super('_renderHtml');},_dispose:function(){this.stopPulling();_.each(this._alertsCollections,function(collection,module){this._clearReminders(module);collection.off();},this);this._alertsCollections={};this._super('_dispose');}})