/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({className:'module-list',recentRowTemplate:Handlebars.compile('{{#each models}}<li><a tabindex="-1" class="recentLink actionLink" href="#{{buildRoute model=this}}" data-route="#{{buildRoute model=this}}"><i class="icon-time active"></i>{{getFieldValue this "name"}}</a></li>{{/each}}'),plugins:['Dropdown'],events:{'click [data-toggle=dropdown]':'getRecentlyViewedAndFavoriteRecords','click .actionLink':'handleMenuEvent',"click a[data-route]":"handleRouteEvent"},handleRouteEvent:function(event){var currentFragment,currentTarget=this.$(event.currentTarget),route=currentTarget.data("route");if(route){if((!_.isUndefined(event.button)&&event.button!==0)||event.ctrlKey||event.metaKey){event.stopPropagation();window.open(route,'_blank');return false;}
event.preventDefault();currentFragment=Backbone.history.getFragment();if(("#"+currentFragment)===route){app.router.refresh();}else{app.router.navigate(route,{trigger:true});}}},handleMenuEvent:function(evt){var $currentTarget=this.$(evt.currentTarget);if($currentTarget.data('event')){var module=$currentTarget.closest('li.dropdown').data('module');app.events.trigger($currentTarget.data('event'),module,evt);}},initialize:function(options){this.activeModule=this._setActiveModule(this);app.events.on("app:sync:complete",this.render,this);app.events.on("app:view:change",this.handleViewChange,this);app.view.View.prototype.initialize.call(this,options);if(this.layout){this.layout.on("view:resize",this.resize,this);}},_dispose:function(){app.view.View.prototype._dispose.call(this);},handleViewChange:function(){this.activeModule.set(app.controller.context.get("module"));this.layout.trigger("header:update:route");},getRecentlyViewedAndFavoriteRecords:function(event){var $currentTarget=$(event.currentTarget),module=$currentTarget.parent().parent().data('module'),moduleMeta=app.metadata.getModule(module);if(!$currentTarget.parent().parent().hasClass('more-drop-container')&&!$currentTarget.hasClass('actionLink')){if(module=='Home'){this.populateDashboards();}
else if(moduleMeta&&moduleMeta.fields&&!_.isArray(moduleMeta.fields)){this.clearFavoritesRecents(module);if(moduleMeta.favoritesEnabled){this.populateFavorites(module);}
this.populateRecents(module);}}},clearFavoritesRecents:function(module){this.$('[data-module='+module+'] .recentContainer').html('');this.$('[data-module='+module+'] .favoritesContainer').html('');},populateFavorites:function(module,populateCallback){var self=this;var filter={"filter":[{"$favorite":""}],"max_num":3};var url=app.api.buildURL(module,'read',{id:"filter"});app.api.call('create',url,filter,{limit:3,success:function(data){if(data.records&&data.records.length>0){if(_.isFunction(populateCallback)){populateCallback();}
var beans=[];_.each(data.records,function(recordData){beans.push(app.data.createBean(module,recordData));});var collection=app.data.createBeanCollection(module,beans);self.$('[data-module='+module+'] .favoritesAnchor').show();var favoritesTemplate=app.template.getView('modulelist.favorites',module)||app.template.getView('modulelist.favorites');self.$('[data-module='+module+'] .favoritesContainer').show().html(favoritesTemplate(collection));}}});},populateRecents:function(module,populateCallback){var self=this;var filter={"filter":[{"$tracker":"-7 DAY"}],"max_num":3};var url=app.api.buildURL(module,'read',{id:"filter"});app.api.call('create',url,filter,{success:function(data){if(data.records&&data.records.length>0){if(_.isFunction(populateCallback)){populateCallback();}
var beans=[];_.each(data.records,function(recordData){beans.push(app.data.createBean(module,recordData));});var collection=app.data.createBeanCollection(module,beans);self.$('[data-module='+module+'] .recentAnchor').show();self.$('[data-module='+module+'] .recentContainer').show().html(self.recentRowTemplate(collection));}}});},populateDashboards:function(){var self=this,sync=function(method,model,options){options=app.data.parseOptionsForSync(method,model,options);var callbacks=app.data.getSyncCallbacks(method,model,options);app.api.records(method,this.apiModule,model.attributes,options.params,callbacks);},Dashboard=app.Bean.extend({sync:sync,apiModule:'Dashboards',module:'Home'}),DashboardCollection=app.BeanCollection.extend({sync:sync,apiModule:'Dashboards',module:'Home',model:Dashboard});var dashCollection=new DashboardCollection();dashCollection.fetch({showAlerts:false,success:function(data){var pattern=/^(LBL|TPL|NTC|MSG)_(_|[a-zA-Z0-9])*$/;_.each(dashCollection.models,function(model){if(pattern.test(model.get('name'))){model.set('name',app.lang.get(model.get('name'),dashCollection.module||null));}});self.$('[data-module=Home] .dashboardContainer').html(self.recentRowTemplate(dashCollection));}});},_renderHtml:function(){if(!app.api.isAuthenticated()||app.config.appStatus=='offline')return;if(!(_.isEmpty(app.metadata.getStrings("mod_strings")))){var self=this;this.module_list={};if(app.metadata.getModuleNames(true,"read")){_.each(app.metadata.getModuleNames(true,"read"),function(val){self.module_list[val]=val;});}
this.module_list=this.completeMenuMeta(this.module_list);app.view.View.prototype._renderHtml.call(this);this.resetMenu();this.activeModule.set(app.controller.context.get("module"));}},completeMenuMeta:function(module_list){var actions,meta,returnList=[],self=this,listLength,fullModuleList=app.metadata.getFullModuleList();_.each(module_list,function(value,key){if(!_.isString(fullModuleList[value])){return;}
actions={label:app.lang.get('LBL_MODULE_NAME',value),name:key};meta=app.metadata.getModule(key);if(meta&&meta.menu&&meta.menu.header){actions.menu=self.filterAvailableMenuActions(meta.menu.header.meta);}else{actions.menu=[];}
listLength=returnList.push(actions);actions.menuIndex=listLength-1;});return returnList;},filterAvailableMenuActions:function(menuMeta){var result=[];_.each(menuMeta,function(menuItem){if(app.acl.hasAccess(menuItem.acl_action,menuItem.acl_module)){result.push(menuItem);}});return result;},resetMenu:function(){this.$('.more').before(this.$('#module_list .more-drop-container').children());},resize:function(width){if(width<=0){return;}
this.activeModule.set(app.controller.context.get("module"));var $activeInMore=this.$('.more').find('.dropdown.active');if($activeInMore.length>0){$activeInMore.find('.btn-group').show();$activeInMore.find('.moreLink').hide();this.$el.find('.dropdown.more').before($activeInMore);}
var $moduleList=this.$el.find('#module_list'),$moduleListClone=$moduleList.clone(),$cloneContainer=$('<div></div>');$cloneContainer.css({position:'absolute',top:'-9999px',display:'block'}).append($moduleListClone);this.$el.append($cloneContainer);if($moduleListClone.outerWidth(true)>=width){this.removeModulesFromList($moduleListClone,width);}else{this.addModulesToList($moduleListClone,width);}
$moduleList.remove();this.$el.append($moduleListClone);$cloneContainer.remove();},addModulesToList:function($modules,width){var $dropdown=$modules.find('.more-drop-container'),$moduleToInsert=$dropdown.children("li:first"),$more=$modules.find('.more'),$lastModuleInList,$nextModule,currentWidth=$modules.outerWidth(true);while((currentWidth<width)&&($dropdown.children().length>0)){$nextModule=$moduleToInsert.next();$moduleToInsert.find('.btn-group').show();$moduleToInsert.find('.moreLink').hide();$lastModuleInList=$more.prev();if(this.activeModule.isActive($lastModuleInList)&&!this.activeModule.isNext($moduleToInsert)){$lastModuleInList.before($moduleToInsert);}else{$more.before($moduleToInsert);}
currentWidth=$modules.outerWidth(true);$moduleToInsert=$nextModule;if(currentWidth>=width){this.removeModulesFromList($modules,width);break;}}
if($dropdown.children().length===0&&$modules.find('.dropdown').is(":visible")){this.$('.more').hide();}},removeModulesFromList:function($modules,width){var $dropdown=$modules.find('.more-drop-container'),$module=$modules.find('.more').prev(),$next,currentWidth=$modules.outerWidth(true),persistentTabs=this.activeModule.isActive($module)?3:2;while(currentWidth>=width&&($modules.children().length-persistentTabs)>0){if(this.activeModule.isActive($module)||$module.hasClass('Home')){$module=$module.prev();}
$next=$module.prev();$dropdown.prepend($module);$module.find('.btn-group').hide();$module.find('.moreLink').show();currentWidth=$modules.outerWidth(true);$module=$next;}
if($dropdown.children().length!==0&&$modules.find('.dropdown').is(":visible")){this.$('.more').show();}},_setActiveModule:function(parent){return{_class:'active',_next:null,_moduleList:parent,set:function(module){var $modules,$module,$next,updateNav=true,mapped;if(app.controller&&app.controller.layout&&app.controller.layout.meta&&!_.isUndefined(app.controller.layout.meta.updateNav)){updateNav=app.controller.layout.meta.updateNav;}
if(module){this.reset();$modules=this._moduleList.$('#module_list');$module=$modules.find("[data-module='"+module+"']");if($module.length<1){mapped=app.metadata.getTabMappedModule(module);if(mapped!==module){$module=$modules.find("[data-module='"+mapped+"']");updateNav=$module.length===0;}
if(updateNav){module=mapped;var moduleList={};moduleList[module]=app.metadata.getFullModuleList()[module];var meta=this._moduleList.completeMenuMeta(moduleList);if(!_.isUndefined(meta[0])){meta[0].menuIndex=-1;var singleMenuTemplate=app.template.get(this._moduleList.name+'.singlemenuPartial');this._moduleList.$el.find('.dropdown.more').before(singleMenuTemplate(meta[0]));$module=$modules.find("[data-module='"+module+"']");}}}
$module.addClass(this._class);if(!this._next){$next=$module.next();if($next.hasClass('more')){$next=$modules.find('.more-drop-container li:first');}
this._next=$next.attr('class');}}},isActive:function($module){return $module.hasClass(this._class);},isNext:function($module){return(this._next===$module.attr('class'));},reset:function(){this.resetActive();this._next=null;this._moduleList.$('.dropdown.'+this._class).removeClass(this._class);},resetActive:function(){var $activeNode=this._moduleList.$('.dropdown.'+this._class);if($activeNode.length<1)return;var beforeIndex=$activeNode.prev().data('menuindex');var activeIndex=$activeNode.data('menuindex');var $afterNode=this._moduleList.$('[data-menuindex='+(activeIndex+1)+']');if(activeIndex==-1){$activeNode.remove();}
if(beforeIndex!=activeIndex-1&&activeIndex!==1){$afterNode.before($activeNode);if($activeNode.parents().hasClass('more')){$activeNode.find('.btn-group').hide();$activeNode.find('.moreLink').show();$activeNode.find('.moreLink').css('display','block');}}}};}})