<?PHP
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN {{$class.name}}
 */

{{foreach from=$class.requires item='require'}}
require_once('{{$require}}');
{{/foreach}}

class {{$class.name}}_sugar extends {{$class.extends}} {
	var $new_schema = true;
	var $module_dir = '{{$class.name}}';
	var $object_name = '{{$class.name}}';
	var $table_name = '{{$class.table_name}}';
	var $importable = {{if $class.importable}}true{{else}}false{{/if}};
	{{foreach from=$class.fields key='field' item='def'}}
	var ${{$field}};
	{{/foreach}}
	{{if empty($class.team_security)}}
	var $disable_row_level_security = true;
	{{/if}}

	/**
	 * This is a depreciated method, please start using __construct() as this method will be removed in a future version
     *
     * @see __construct
     * @depreciated
	 */
	function {{$class.name}}_sugar(){
		self::__construct();
	}

	public function __construct(){
		parent::__construct();
	}
	
	{{if $class.acl}}
public function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
	{{/if}}
	
}
?>