<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Trackers/Dashlets/TrackerDashlet/TrackerDashlet.tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dashletStrings = array ( 
   'TrackerDashlet' => array (
      'LBL_TITLE' => 'Takip Raporları' ,
      'LBL_DESCRIPTION' => 'Takip verileri üstünde sorgular çalıştırmaya yarayan bir dashlet' ,
      'LBL_SAVING' => 'Sorgu Çalıştırılıyor ...' ,
      'LBL_SAVED' => 'Sorgu Tamamlandı' ,
      'LBL_CLEAR' => 'Temizle' ,
      'LBL_CLEAR_TOOLTIP' => 'Tarih alanındaki bilgiyi temizler' ,
      'LBL_CONFIGURE_TITLE' => 'Başlık' ,
      'LBL_CONFIGURE_HEIGHT' => 'Yüksekliği (1-300)' ,
      'LBL_SELECT_QUERY' => 'Sorgu Seç...' ,
      'LBL_FILTER' => 'Filtre' ,
      'LBL_FILTER_TOOLTIP' => 'Tarih alanındaki bilgiye göre filtreler' ,
      'LBL_SINCE' => '-Ten Beri:' ,
      'LBL_CHOOSE_DATE_TOOLTIP' => 'Seçilen raporlar için bir tarih filtresi belirtilebilirsiniz. Girilen tarih bilgisi, raporda varsayılan tarih bilgisinin yerine geçecektir. Örneğin  "Aktivitelerim (Bu hafta)" raporunda, varsayılan tarih aralığı olan bir hafta yerine, belirtilen filtre tarih bilgisinden sonra olan tüm kayıtlar görüntülenir.'   ));

?>
