/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
({className:'list-view',events:{'click [class*="orderBy"]':'setOrderBy'},defaultLayoutEvents:{"list:search:fire":"fireSearch","list:paginate:success":"paginateSuccess","list:filter:toggled":"filterToggled","list:alert:show":"showAlert","list:alert:hide":"hideAlert","list:sort:fire":"sort"},defaultContextEvents:{},_previewed:null,_leftActions:[],_rowActions:[],_fields:{},initialize:function(options){var listViewMeta=app.metadata.getView(options.module,'list')||{};options.meta=_.extend({},listViewMeta,options.meta||{});options.meta.type=options.meta.type||'list';options.meta.action='list';options=this.parseFieldMetadata(options);app.view.View.prototype.initialize.call(this,options);this.attachEvents();this.orderByLastStateKey=app.user.lastState.key('order-by',this);this.orderBy=_.extend({field:'',direction:'desc'},listViewMeta.orderBy,app.user.lastState.get(this.orderByLastStateKey)||{});if(this.collection){this.collection.orderBy=this.orderBy;}
this.limit=this.context.has('limit')?this.context.get('limit'):null;},parseFieldMetadata:function(options){_.each(options.meta.panels,function(panel,panelIdx){_.each(panel.fields,function(field,fieldIdx){if(!_.isUndefined(field.align)){var alignClass='';if(_.contains(['left','center','right'],field.align)){alignClass='t'+field.align;}
options.meta.panels[panelIdx].fields[fieldIdx].align=alignClass;}
if(!_.isUndefined(field.width)){var parts=field.width.toString().match(/^(\d{0,3})\%$/);var widthValue='';if(parts){if(parseInt(parts[1])<100){widthValue=parts[0];}}
options.meta.panels[panelIdx].fields[fieldIdx].width=widthValue;}},this);},this);return options;},attachEvents:function(){this.layoutEventsMap=_.extend(this.defaultLayoutEvents,this.layoutEvents);this.contextEventsMap=_.extend(this.defaultContextEvents,this.contextEvents);if(this.layout){_.each(this.layoutEventsMap,function(callback,event){this.layout.on(event,this[callback],this);},this);}
if(this.context){_.each(this.contextEventsMap,function(callback,event){this.context.on(event,this[callback],this);},this);}},paginateSuccess:function(){app.events.trigger("preview:collection:change",this.collection);if(!this.disposed)this.render();},sort:function(){app.events.trigger("preview:close");},parseFields:function(viewMeta){this._fields={"default":[],"available":{"visible":[],"all":[]}};_.each(viewMeta.panels,function(panel){_.each(panel.fields,function(fieldMeta,i){if(fieldMeta["default"]===false){this._fields["available"].all.push(fieldMeta.name);}else{this._fields["default"].push(fieldMeta.name);}},this);},this);return viewMeta;},showAlert:function(message){this.$(".alert .container").html(message);this.$(".alert").removeClass("hide");},hideAlert:function(){this.$(".alert").addClass("hide");},filterToggled:function(isOpened){this.filterOpened=isOpened;},fireSearch:function(term){term=term||"";var options={limit:this.limit||null,query:term};this.context.get("collection").resetPagination();this.context.resetLoadFlag(false);this.context.set('skipFetch',false);this.context.loadData(options);},setOrderBy:function(event){var collection,options,eventTarget,orderBy;var self=this;collection=self.collection;eventTarget=self.$(event.currentTarget);orderBy=eventTarget.data('orderby');if(!orderBy){orderBy=eventTarget.data('fieldname');}
if(orderBy===self.orderBy.field){self.orderBy.direction=self.orderBy.direction==='desc'?'asc':'desc';}else{self.orderBy.field=orderBy;self.orderBy.direction='desc';}
collection.orderBy=self.orderBy;options=self.getSortOptions(collection);if(this.orderByLastStateKey){app.user.lastState.set(this.orderByLastStateKey,self.orderBy);}
self.context.resetLoadFlag(false);self.context.set('skipFetch',false);self.context.loadData(options);},getSortOptions:function(collection){var self=this,options={};options=self.filterOpened?self.getSearchOptions():{};options.showAlerts=true;options.limit=self.limit||null;options.success=function(collection,response,options){self.layout.trigger("list:sort:fire",collection,self);if(!self.disposed)collection.reset(response);};if(collection.offset){options.limit=collection.offset;options.offset=0;}
return options;},getSearchOptions:function(){var collection,options,previousTerms,term='';collection=this.context.get('collection');if(app.cache.has('previousTerms')){previousTerms=app.cache.get('previousTerms');if(previousTerms){term=previousTerms[this.module];}}
options={params:{},fields:collection.fields?collection.fields:this.collection};if(term){options.params.q=term;}
if(this.context.get('link')){options.relate=true;}
return options;},bindDataChange:function(){if(this.collection){this.collection.on("reset",this.render,this);}},_dispose:function(){this._fields=null;app.view.View.prototype._dispose.call(this);}})