/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
({fieldTag:"input",plugins:['EllipsisInline'],defaultOnUndefined:true,BLANK_VALUE_ID:'___i_am_empty___',bindKeyDown:function(callback){this.$('input').on("keydown.record",{field:this},callback);},_render:function(){var self=this;if(_.isUndefined(this.items)){this.loadEnumOptions(false,function(){if(!this.disposed){this.render();}});}
if(this.def.isMultiSelect&&!_.isUndefined(this.items[''])&&this.items['']===''){var obj={};_.each(this.items,function(value,key){if(key!==''&&value!==''){obj[key]=value;}},this);this.items=obj;}
var optionsKeys=_.isObject(this.items)?_.keys(this.items):[];if(this.defaultOnUndefined&&!this.def.isMultiSelect&&_.isUndefined(this.model.get(this.name))){var defaultValue=_.first(optionsKeys);if(defaultValue){this.model.set(this.name,defaultValue);}}
app.view.Field.prototype._render.call(this);var select2Options=this.getSelect2Options(optionsKeys);var $el=this.$(this.fieldTag);if(!_.isEmpty(optionsKeys)){if(this.tplName==='edit'||this.tplName==='list-edit'){$el.select2(select2Options);$el.select2("container").addClass("tleft");$el.on('change',function(ev){var value=ev.val;if(self.model&&!(self.name=='currency_id'&&_.isUndefined(value))){self.model.set(self.name,self.unformat(value));}});if(this.def.ordered){$el.select2("container").find("ul.select2-choices").sortable({containment:'parent',start:function(){$el.select2("onSortStart");},update:function(){$el.select2("onSortEnd");}});}}else if(this.tplName==='disabled'){$el.select2(select2Options);$el.select2('disable');}
if(this.value){if(!_.isArray(this.value)){this.value=[this.value];}
$el.select2('val',this.value);}}else{this.$el.html(app.lang.get("LBL_LOADING"));}
return this;},focus:function(){if(this.action!=='disabled'&&!this.def.isMultiSelect){this.$(this.fieldTag).select2('open');}},loadEnumOptions:function(fetch,callback){var self=this,meta=app.metadata.getModule(this.module,'fields'),fieldMeta=meta&&meta[this.name]?meta[this.name]:this.def;this.items=this.def.options||fieldMeta.options;fetch=fetch||false;if(fetch||_.isUndefined(this.items)){var _key='request:'+this.module+':'+this.name;if(this.context.get(_key)){var request=this.context.get(_key);request.xhr.done(_.bind(function(o){if(this.items!==o){this.items=o;callback.call(this);}},this));}else{var request=app.api.enumOptions(self.module,self.name,{success:function(o){if(self.disposed){return;}
if(self.items!==o){self.items=o;fieldMeta.options=self.items;self.context.unset(_key);callback.call(self);}}});this.context.set(_key,request);}}else if(_.isString(this.items)){this.items=app.lang.getAppListStrings(this.items);}},getSelect2Options:function(optionsKeys){var select2Options={};var emptyIdx=_.indexOf(optionsKeys,"");if(emptyIdx!==-1){select2Options.allowClear=true;if(emptyIdx>1){this.hasBlank=true;}}
if(!this.def.isMultiSelect){select2Options.placeholder=app.lang.get("LBL_SEARCH_SELECT");}
if(_.isEmpty(optionsKeys)){select2Options.placeholder=app.lang.get("LBL_LOADING");}
select2Options.width=this.def.enum_width?this.def.enum_width:'100%';select2Options.dropdownCssClass=this.def.dropdown_class?this.def.dropdown_class:'';select2Options.containerCssClass=this.def.container_class?this.def.container_class:(this.def.isMultiSelect?'select2-choices-pills-close':'');if(this.def.dropdown_width){select2Options.dropdownCss={width:this.def.dropdown_width};}
select2Options.minimumResultsForSearch=this.def.searchBarThreshold?this.def.searchBarThreshold:7;if(this.def.isMultiSelect){select2Options.multiple=true;}
select2Options.separator=this.def.separator||',';if(this.def.separator){select2Options.tokenSeparators=[this.def.separator];}
select2Options.initSelection=_.bind(this._initSelection,this);select2Options.query=_.bind(this._query,this);return select2Options;},_initSelection:function($ele,callback){var data=[];var options=_.isString(this.items)?app.lang.getAppListStrings(this.items):this.items;var values=$ele.val();if(this.def.isMultiSelect){values=values.split(this.def.separator||',');}
_.each(_.pick(options,values),function(value,key){data.push({id:key,text:value});},this);if(data.length===1){callback(data[0]);}else{callback(data);}},_query:function(query){var options=_.isString(this.items)?app.lang.getAppListStrings(this.items):this.items;var data={results:[],more:false};if(_.isObject(options)){_.each(options,function(element,index){var text=""+element;if(query.matcher(query.term,text)){data.results.push({id:index,text:text});}});}else{options=null;}
query.callback(data);},unformat:function(value){if(this.def.isMultiSelect&&_.isArray(value)&&_.indexOf(value,this.BLANK_VALUE_ID)>-1){value=_.clone(value);delete value[this.BLANK_VALUE_ID];}
if(this.def.isMultiSelect&&_.isNull(value)){return[];}else{return value;}},format:function(value){if(this.def.isMultiSelect&&_.isArray(value)&&_.indexOf(value,'')>-1){value=_.clone(value);delete value[''];}
if(this.def.isMultiSelect&&_.isString(value)){return this.convertMultiSelectDefaultString(value);}else{return value;}},convertMultiSelectDefaultString:function(defaultString){var result=defaultString.split(",");_.each(result,function(value,key){if(value!=='^^'){result[key]=value.replace(/\^/g,"");}});return result;},bindDomChange:function(){},unbindDom:function(){this.$(this.fieldTag).select2('destroy');app.view.Field.prototype.unbindDom.call(this);},unbindData:function(){var _key='request:'+this.module+':'+this.name;this.context.unset(_key);app.view.Field.prototype.unbindData.call(this);}})