/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
(function(app){var _useRequiredLabels={"bool":true,"radioenum":'edit'};app.events.on("app:init",function(){var _fieldProto=_.clone(app.view.Field.prototype);_.extend(app.view.Field.prototype,{exclamationMarkTemplate:Handlebars.compile('<span class="error-tooltip add-on" data-container="body" rel="tooltip" title="{{arrayJoin this ", "}}"><i class="icon-exclamation-sign"></i></span>'),handleValidationError:function(errors){this.clearErrorDecoration();_.defer(function(field){field._errors=errors;field.setMode('edit');if(!field._shouldRenderRequiredPlaceholder()){field.decorateRequired();}
field.decorateError(errors);},this);this.$el.off("keydown.record");$(document).off("mousedown.record"+this.name);},_removeViewClass:function(action){this.$el.removeClass(action);},_addViewClass:function(action){this.$el.addClass(action);},showNoData:function(){return this.def.readonly&&this.name&&!this.model.has(this.name);},_checkAccessToAction:function(action){if(_.contains(this.fallbackActions,action)&&_.isUndefined(this.viewFallbackMap[action])){return true;}
if(_.result(this,'showNoData')===true){return action==='nodata';}
return app.acl.hasAccessToModel(action,this.model,this.name);},viewFallbackMap:{'list':'detail','edit':'detail','detail':'noaccess','noaccess':'nodata'},fallbackActions:['noaccess','nodata'],_getFallbackTemplate:function(viewName){if(_.contains(this.fallbackActions,viewName)){return viewName;}
return(this.isDisabled()&&viewName==='disabled')?'edit':(this.view.fallbackFieldTemplate||'detail');},_render:function(){var $tooltip=this.$('.error-tooltip');if(_.isFunction($tooltip.tooltip)){$tooltip.tooltip('destroy');}
var isErrorState=this.$('.add-on.error-tooltip').length>0;_fieldProto._render.call(this);if(this._previousAction){this._addViewClass(this._previousAction);}
this._addViewClass(this.action);if(isErrorState){this.decorateError(this._errors);}
if(this.def.required){this.clearRequiredLabel();if((this.action==='edit'||-1!==_.indexOf(['edit','list-edit'],this.tplName))&&this._shouldRenderRequiredPlaceholder()){this.decorateRequired();}}
if(this.def.help){this.clearHelper();if(this.action==='edit'||-1!==_.indexOf(['edit','list-edit'],this.tplName)){this.decorateHelper();}}},clearHelper:function(){this.$el.closest('.record-cell').attr({'rel':''});},decorateHelper:function(){this.$el.closest('.record-cell').attr({'rel':'tooltip','data-title':this.def['help'],'data-placement':'bottom'});},_shouldRenderRequiredPlaceholder:function(){return!this.def.no_required_placeholder;},decorateRequired:function(){var useLabels=_useRequiredLabels[this.type];useLabels=_.isString(useLabels)?(useLabels===this.tplName):useLabels;if(useLabels){this.setRequiredLabel();}else{this.setRequiredPlaceholder();}},setRequiredPlaceholder:function(element){var el=element||this.$(this.fieldTag).first();var old=el.attr("placeholder");var requiredPlaceholder=app.lang.get("LBL_REQUIRED_FIELD",this.module);var newPlaceholder=requiredPlaceholder;if(old){newPlaceholder=old+" ("+requiredPlaceholder+")";}
el.attr("placeholder",newPlaceholder).addClass("required");},setRequiredLabel:function(element){var ele=element||this.$el;var $label=ele.closest('.record-cell').find(".record-label");$label.append(' <span data-required="required">('+app.lang.get("LBL_REQUIRED_FIELD",this.module)+')</span>');},clearRequiredLabel:function(element){var ele=element||this.$el;var $label=ele.closest('.record-cell').find('span[data-required]');$label.remove();},setMode:function(name){var oldAction=this._previousAction||this.action;this._removeViewClass(oldAction);_fieldProto.setMode.call(this,name);},setDisabled:function(disable){if(!this._checkAccessToAction('disabled')){return;}
disable=_.isUndefined(disable)?true:disable;if(disable===false&&this.isDisabled()){this._removeViewClass(this.action);}
_fieldProto.setDisabled.call(this,disable);},decorateError:function(errors){var ftag=this.fieldTag||'',$ftag=this.$(ftag),errorMessages=[],$tooltip;this.$el.closest('.record-cell').addClass('error');this.$el.addClass('error');if(_.isString(errors)){errorMessages.push(errors);}else{_.each(errors,function(errorContext,errorName){errorMessages.push(app.error.getErrorString(errorName,errorContext));});}
$ftag.wrap('<div class="input-append error '+ftag+'">');$tooltip=this.exclamationMarkTemplate(errorMessages);$ftag.after($tooltip);if(_.isFunction($tooltip.tooltip)){var tooltipOpts={placement:'top',trigger:'click'};$tooltip.tooltip(tooltipOpts);}
$ftag.each(function(){if($(this).hasClass("select2-offscreen")){$(this).parent("div.input-append.error").addClass("select2-offscreen");}});},clearErrorDecoration:function(){var ftag=this.fieldTag||'',$ftag=this.$(ftag);this.$('.add-on').remove();var isWrapped=$ftag.parent().hasClass('input-append');if(isWrapped){$ftag.unwrap();}
this.$el.removeClass(ftag);this.$el.removeClass("error");this.$el.closest('.record-cell').removeClass("error");},delegateEvents:function(events){events=events||this.events||(this.def?this.def.events:null);if(!events){return;}
events['click a[href="javascript:void(0)"]']='_handleBadLinkHref';events['click a[href="javascript:void(0);"]']='_handleBadLinkHref';_fieldProto.delegateEvents.call(this,events);},_handleBadLinkHref:function(evt){evt.preventDefault();}});});})(SUGAR.App);