/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
(function(app){app.events.on("app:init",function(){app.utils=_.extend(app.utils,{tooltip:{initialize:function($elements,options){return $elements.tooltip(_.extend({},{container:'body',trigger:'hover'},options));},destroy:function($tooltips){if($tooltips){_.each($tooltips,function(tooltip){if(this.has(tooltip)){$(tooltip).tooltip('destroy');}},this);}},has:function(element){return!_.isUndefined($(element).data('tooltip'));}},createHistoryLog:function(oldestModel,newestModel){var is_first_commit=false;if(_.isEmpty(oldestModel)){oldestModel=new Backbone.Model({best_case:0,likely_case:0,worst_case:0,date_entered:''});is_first_commit=true;}
var best_difference=this.getDifference(oldestModel,newestModel,'best_case'),best_direction=this.getDirection(best_difference),likely_difference=this.getDifference(oldestModel,newestModel,'likely_case'),likely_direction=this.getDirection(likely_difference),worst_difference=this.getDifference(oldestModel,newestModel,'worst_case'),worst_direction=this.getDirection(worst_difference),args=[],text='LBL_COMMITTED_HISTORY_NONE_CHANGED',best_arrow=this.getArrowDirectionSpan(best_direction),likely_arrow=this.getArrowDirectionSpan(likely_direction),worst_arrow=this.getArrowDirectionSpan(worst_direction),num_shown=0,hb=Handlebars.compile("{{{str key module args}}}"),lang_string_key='',final_args=[],labels=[],setup_or_updated_lang_key=(is_first_commit)?'_SETUP':'_UPDATED',likely_args={changed:likely_difference!=0,show:app.metadata.getModule('Forecasts','config').show_worksheet_likely},best_args={changed:best_difference!=0,show:app.metadata.getModule('Forecasts','config').show_worksheet_best},worst_args={changed:worst_difference!=0,show:app.metadata.getModule('Forecasts','config').show_worksheet_worst};likely_args.show?num_shown++:'';best_args.show?num_shown++:'';worst_args.show?num_shown++:'';lang_string_key='LBL_COMMITTED_HISTORY_'+num_shown+'_SHOWN';if(likely_args.changed&&likely_args.show){final_args.push(this.gatherLangArgsByParams(likely_direction,likely_arrow,likely_difference,newestModel,'likely_case'));}else if(likely_args.show){final_args.push([]);}
if(best_args.changed&&best_args.show){final_args.push(this.gatherLangArgsByParams(best_direction,best_arrow,best_difference,newestModel,'best_case'));}else if(best_args.show){final_args.push([]);}
if(worst_args.changed&&worst_args.show){final_args.push(this.gatherLangArgsByParams(worst_direction,worst_arrow,worst_difference,newestModel,'worst_case'));}else if(worst_args.show){final_args.push([]);}
labels=this.getCommittedHistoryLabel(best_args,likely_args,worst_args,is_first_commit);final_args=this.parseArgsAndLabels(final_args,labels);var text=hb({'key':lang_string_key,'module':"Forecasts",'args':final_args});return{'text':new Handlebars.SafeString(text)};},gatherLangArgsByParams:function(dir,arrow,diff,model,attrStr){return{'direction':new Handlebars.SafeString(app.lang.get(dir,'Forecasts')+arrow),'from':app.currency.formatAmountLocale(Math.abs(diff)),'to':app.currency.formatAmountLocale(model.get(attrStr))};},getArrowDirectionSpan:function(directionClass){return directionClass=="LBL_UP"?'&nbsp;<i class="icon-arrow-up font-green"></i>':directionClass=="LBL_DOWN"?'&nbsp;<i class="icon-arrow-down font-red"></i>':'';},getArrowIconColorClass:function(newValue,oldValue){var diff=Math.abs(newValue-oldValue),cls='';if(diff>=0.01){cls=(newValue>oldValue)?' icon-arrow-up font-green':' icon-arrow-down font-red';}
return cls;},getForecastType:function(isManager,showOpps){return(!showOpps&&isManager)?'Rollup':'Direct';},getCommittedHistoryLabel:function(best,likely,worst,is_first_commit){var args=[];if(is_first_commit){args.push('LBL_COMMITTED_HISTORY_SETUP_FORECAST');}else{args.push('LBL_COMMITTED_HISTORY_UPDATED_FORECAST');}
if(likely.show){if(likely.changed){args.push('LBL_COMMITTED_HISTORY_LIKELY_CHANGED');}else{args.push('LBL_COMMITTED_HISTORY_LIKELY_SAME');}}
if(best.show){if(best.changed){args.push('LBL_COMMITTED_HISTORY_BEST_CHANGED');}else{args.push('LBL_COMMITTED_HISTORY_BEST_SAME');}}
if(worst.show){if(worst.changed){args.push('LBL_COMMITTED_HISTORY_WORST_CHANGED');}else{args.push('LBL_COMMITTED_HISTORY_WORST_SAME');}}
return args;},parseArgsAndLabels:function(argsArray,labels){var retArgs={},argsKeys=['first','second','third'],hb=Handlebars.compile("{{{str key module args}}}");if((argsArray.length+1)!=labels.length){app.logger.error('ForecastsUtils.parseArgsAndLabels() :: argsArray and labels params are not the same length ');return null;}
retArgs.intro=hb({'key':_.first(labels),'module':'Forecasts','args':[]});labels=_.last(labels,labels.length-1);_.each(labels,function(label,index){retArgs[argsKeys[index]]=hb({'key':label,'module':'Forecasts','args':argsArray[index]});});return retArgs;},getDifference:function(oldModel,newModel,attr){var diff=newModel.get(attr)-oldModel.get(attr);return(Math.abs(diff)<0.01)?0:diff;},getDirection:function(difference){return difference>0?'LBL_UP':(difference<0?'LBL_DOWN':'');},getSubpanelList:function(module){var list={},subpanels=app.metadata.getModule(module).layouts.subpanels;if(subpanels&&subpanels.meta&&subpanels.meta.components){_.each(subpanels.meta.components,function(comp){if(comp.context&&comp.context.link){list[comp.label]=comp.context.link;}else{app.logger.warning("Subpanel's subpanels.meta.components has component with no context or context.link");}});}
return list;},isRequiredLink:function(module,link){var relatedFields=app.data.getRelateFields(module,link);var requiredField=_.some(relatedFields,function(field){return field.required===true;},this);return requiredField;},getAppConfigDatasets:function(app_list_dataset_name,cfg_key_prefix){var ds=app.metadata.getStrings('app_list_strings')[app_list_dataset_name]||[];var returnDs={};_.each(ds,function(value,key){if(app.metadata.getModule('Forecasts','config')[cfg_key_prefix+key]==1){returnDs[key]=value}},this);return returnDs;},_tableColumnsConfigKeyMapManager:{'likely_case':'show_worksheet_likely','likely_case_adjusted':'show_worksheet_likely','best_case':'show_worksheet_best','best_case_adjusted':'show_worksheet_best','worst_case':'show_worksheet_worst','worst_case_adjusted':'show_worksheet_worst'},_tableColumnsConfigKeyMapRep:{'likely_case':'show_worksheet_likely','best_case':'show_worksheet_best','worst_case':'show_worksheet_worst'},getColumnVisFromKeyMap:function(key,viewName){var moduleMap={'forecastsWorksheet':'rep','forecastsWorksheetTotals':'rep','forecastsWorksheetManager':'mgr','forecastsWorksheetManagerTotals':'mgr'};var whichKeyMap=moduleMap[viewName];var keyMap=(whichKeyMap==='rep')?this._tableColumnsConfigKeyMapRep:this._tableColumnsConfigKeyMapManager;var returnValue=app.metadata.getModule('Forecasts','config')[keyMap[key]];if(!_.isUndefined(returnValue)){returnValue=returnValue==1}else{returnValue=true;}
return returnValue;},getSelectedUsersReportees:function(selectedUser,context){if(selectedUser.isManager){if(_.isUndefined(selectedUser.reportees)){selectedUser.reportees=[];}
var url=app.api.buildURL('Users','filter'),post_args={"filter":[{"reports_to_id":selectedUser.id}],"fields":"full_name"},options={};options.success=_.bind(function(resp,status,xhr){_.each(resp.records,function(user){selectedUser.reportees.push({id:user.id,name:user.full_name});});this.set("selectedUser",selectedUser)},context);app.api.call("create",url,post_args,options);}else{context.set("selectedUser",selectedUser);}},checkForecastConfig:function(){var forecastConfigOK=true,cfg=app.metadata.getModule('Forecasts','config'),salesWonVals=cfg.sales_stage_won,salesLostVals=cfg.sales_stage_lost,salesWonLostVals=cfg.sales_stage_won.concat(cfg.sales_stage_lost),domVals=app.lang.getAppListStrings('sales_stage_dom');if(salesWonVals.length==0||salesLostVals.length==0||_.isEmpty(domVals)){forecastConfigOK=false;}else{forecastConfigOK=_.every(salesWonLostVals,function(val){return(val!=''&&_.has(domVals,val));},this);}
return forecastConfigOK;},isTouchDevice:function(){return Modernizr.touch;},customBuildRoute:function(moduleOrContext,id,action,inBwc){var module,moduleMeta;if(_.isEmpty(moduleOrContext)){return'';}
if(_.isString(moduleOrContext)){module=moduleOrContext;}else{module=moduleOrContext.get('module');}
if(_.isEmpty(module)||!app.bwc){return'';}
moduleMeta=app.metadata.getModule(module)||{};if(inBwc===false||(_.isUndefined(inBwc)&&!moduleMeta.isBwcEnabled)){return'';}
return app.bwc.buildRoute(module,id,app.bwc.getAction(action));},addIframeMark:function(url){var parts=url.split("?");if(parts[1]&&parts[1].indexOf('bwcFrame=1')!=-1)return url;return parts[0]+"?"+(parts[1]?parts[1]+"&bwcFrame=1":"bwcFrame=1");},rmIframeMark:function(url){var parts=url.split("?");if(!parts[1]){return url;}
return parts[0]+"?"+_.reduce(parts[1].split("&"),function(acc,item){if(item=='bwcFrame=1'){return acc;}else{return acc?acc+"&"+item:item;}},'');},getSubpanelCollection:function(ctx,module){var retCollection=undefined,mdl=_.find(ctx.children,function(child){return(child.get('module')==module);});if(mdl&&_.has(mdl.attributes,'collection')){retCollection=mdl.get('collection');}
return retCollection;}});});})(SUGAR.App);