<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SavedSearch/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_MODULE_TITLE' => 'Kaydedilmiş Aramalarım' ,
   'LBL_SEARCH_FORM_TITLE' => 'Kaydedilmiş Aramalarım: Ara' ,
   'LBL_LIST_FORM_TITLE' => 'Kaydedilmiş Aramalarımın Listesi' ,
   'LBL_DELETE_CONFIRM' => 'Seçilen Kaydedilmiş Aramayı silmek istediğinizden emin misiniz?' ,
   'LBL_UPDATE_BUTTON_TITLE' => 'Bu Kaydedilmiş Aramayı Güncelle' ,
   'LBL_DELETE_BUTTON_TITLE' => 'Kaydedilmiş Aramayı Sil' ,
   'LBL_SAVE_BUTTON_TITLE' => 'Şu anki aramayı Kaydet' ,
   'LBL_LIST_NAME' => 'İsim' ,
   'LBL_LIST_MODULE' => 'Modül' ,
   'LBL_ORDER_BY_COLUMNS' => 'Kolona göre sırala:' ,
   'LBL_DIRECTION' => 'Yön:' ,
   'LBL_SAVE_SEARCH_AS' => 'Aramayı şu adla kaydet:' ,
   'LBL_SAVE_SEARCH_AS_HELP' => 'Detaylı Arama Sekmesindeki görüntü seçeneklerini ve filtreleri kaydeder.' ,
   'LBL_PREVIOUS_SAVED_SEARCH' => 'Önceden Kaydedilmiş Aramalar:' ,
   'LBL_PREVIOUS_SAVED_SEARCH_HELP' => 'Var olan Kaydedilmiş Aramayı Değiştir veya Sil.' ,
   'LBL_ASCENDING' => 'Artan' ,
   'LBL_DESCENDING' => 'Azalan' ,
   'LBL_MODIFY_CURRENT_SEARCH' => 'Şu anki aramayı değiştir' );

?>
