<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Relationships/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_ID' => 'İlişki ID' ,
   'LBL_RELATIONSHIP_NAME' => 'İlişki İsmi' ,
   'LBL_LHS_MODULE' => 'LHS Modül İsmi' ,
   'LBL_LHS_TABLE' => 'LHS Tablo İsmi' ,
   'LBL_LHS_KEY' => 'LHS Anahtar İsmi' ,
   'LBL_RHS_MODULE' => 'RHS Modül İsmi' ,
   'LBL_RHS_TABLE' => 'RHS Tablo İsmi' ,
   'LBL_RHS_KEY' => 'RHS Anahtar İsmi' ,
   'LBL_JOIN_TABLE' => 'Bağlayıcı Tablo İsmi' ,
   'LBL_JOIN_KEY_LHS' => 'Bağlayıcı Anahtar LHS' ,
   'LBL_JOIN_KEY_RHS' => 'Bağlayıcı Anahtar RHS' ,
   'LBL_RELATIONSHIP_TYPE' => 'İlişki Tipi' ,
   'LBL_RELATIONSHIP_ROLE_COLUMN' => 'İlişkili Rolün Kolon İsmi' ,
   'LBL_RELATIONSHIP_ROLE_COLUMN_VALUE' => 'İlişkili Rolün Kolon Değeri' ,
   'LBL_REVERSE' => 'Ters' ,
   'LBL_DELETED' => 'Silindi' );

?>
