/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
({extendsFrom:'RowactionField',shareTplSubject:null,shareTplBody:null,shareTplBodyHtml:null,initialize:function(options){options.def=options.def||{};this.events=_.extend({},this.events,options.def.events||{},{'click a[name="share"][data-event="true"]':'share'});app.view.invokeParent(this,{type:'field',name:'rowaction',method:'initialize',args:[options]});this._initShareTemplates();if(app.user.getPreference('use_sugar_email_client')!=='true'){options.def.href=this._shareWithMailTo();}},_initShareTemplates:function(){this.shareTplSubject=app.template.getView('share.subject',this.module)||app.template.getView('share.subject');this.shareTplBody=app.template.getView('share.body',this.module)||app.template.getView('share.body');this.shareTplBodyHtml=app.template.getView('share.body-html',this.module)||app.template.getView('share.body-html');},_getShareParams:function(){var moduleString=app.lang.getAppListStrings('moduleListSingular');return _.extend({},this.model.attributes,{module:moduleString[this.module]||this.module,appId:app.config.appId,url:window.location.href,name:this.model.attributes.name||this.model.attributes.full_name});},share:function(){this._shareWithSugarEmailClient();},_shareWithSugarEmailClient:function(){var subject=this.shareTplSubject(this._getShareParams()),body=this.shareTplBody(this._getShareParams()),bodyHtml=this.shareTplBodyHtml(this._getShareParams());app.drawer.open({layout:'compose',context:{create:true,module:'Emails',model:app.data.createBean('Emails',{subject:subject,html_body:bodyHtml||body})}});},_shareWithMailTo:function(){var subject=this.shareTplSubject(this._getShareParams()),body=this.shareTplBody(this._getShareParams());return'mailto:?'+['subject='+encodeURIComponent(subject),'body='+encodeURIComponent(body)].join('&');}})