/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({tagName:'iframe',className:'bwc-frame',id:'bwc-frame',moduleRegex:new RegExp('module=([^&]*)'),idRegex:new RegExp('record=([^&]*)'),actionRegex:new RegExp('action=([^&]*)'),plugins:['Editable'],warnEnabledBwcActions:['editview','config'],initialize:function(options){var url=options.context.get('url');if(url&&(url.search(/module=Home.*action=index/)>-1||url.search(/action=index.*module=Home/)>-1)){app.router.navigate('#Home',{trigger:true});return;}
this.$el.attr('src',app.utils.addIframeMark(options.context.get('url')||'index.php?module='+this.options.module+'&action=index'));app.view.View.prototype.initialize.call(this,options);this.bwcModel=app.data.createBean('bwc');},hasUnsavedChanges:function(){var bwcWindow=this.$el.get(0).contentWindow;if(_.isEmpty(this.bwcModel.attributes)){return false;}
var newAttributes=this.serializeObject(bwcWindow.EditView);return!_.isEmpty(this.bwcModel.changedAttributes(newAttributes));},serializeObject:function(theForm){var formArray=$(theForm).serializeArray();return _.reduce(formArray,function(acc,field){acc[field.name]=field.value;return acc;},{});},_render:function(){if(this.module==='Administration'&&!app.acl.hasAccessToAny('admin')&&!app.acl.hasAccessToAny('developer')){app.logger.info('Current user does not have access to this module view. name: '+
this.name+' module:'+this.module);app.error.handleRenderError(this,'view_render_denied');app.router.navigate('#Home',{trigger:true});return;}
app.view.View.prototype._render.call(this);return this;},_renderHtml:function(){var self=this;app.view.View.prototype._renderHtml.call(this);this.$el.load(function(){self._setModule(this.contentWindow);self._setBwcModel(this.contentWindow);var url='#bwc/index.php'+this.contentWindow.location.search;self._setCurrentUrl(url);if(this.contentWindow.$===undefined){return;}
self._rewriteLinksForSidecar(this.contentWindow);self._rewriteNewWindowLinks(this.contentWindow);self._cloneBodyClasses(this.contentWindow);self._resizeIframe(this.contentWindow);});},_cloneBodyClasses:function(contentWindow){contentWindow.$('html').addClass($('html').prop('class'));},_setModule:function(contentWindow){var module=this.moduleRegex.exec(contentWindow.location.search);module=(_.isArray(module))?module[1]:null;if(!module){if(contentWindow.$&&contentWindow.$('input[name="module"]')&&contentWindow.$('input[name="module"]').val()){module=contentWindow.$('input[name="module"]').val();}else{return;}}
if(module==='Import'){var importModule=/import_module=([^&]*)/.exec(contentWindow.location.search);if(!_.isNull(importModule)&&!_.isEmpty(importModule[1])){module=importModule[1];}}
var app=window.parent.SUGAR.App;app.controller.context.set('module',module);app.events.trigger('app:view:change',this.layout,{module:module});},_resizeIframe:function(contentWindow){if(Modernizr.touch){$('.bwc-frame').css('height',contentWindow.$("#main").height());}},_setBwcModel:function(contentWindow){var action=this.actionRegex.exec(contentWindow.location.search);action=(_.isArray(action))?action[1].toLowerCase():null;if(contentWindow.EditView){action='editview';}
var attributes={};if(_.contains(this.warnEnabledBwcActions,action)){attributes=this.serializeObject(contentWindow.EditView);}
this.resetBwcModel(attributes);},_setCurrentUrl:function(url){url=app.utils.rmIframeMark(url);this._currentUrl=url;window.parent.location.hash=url;},revertBwcModel:function(){var bwcWindow=this.$el.get(0).contentWindow;var newAttributes=this.serializeObject(bwcWindow.EditView);this.resetBwcModel(newAttributes);},resetBwcModel:function(attr){this.bwcModel.clear({silent:true}).set(attr);},convertToSidecarUrl:function(href){var module=this.moduleRegex.exec(href),id=this.idRegex.exec(href),action=this.actionRegex.exec(href);module=(_.isArray(module))?module[1]:null;if(!module){return'';}
if(app.metadata.getModule(module).isBwcEnabled){href=href.replace(/^.\//,'');return"bwc/"+href;}
id=(_.isArray(id))?id[1]:null;action=(_.isArray(action))?action[1]:'';if(action.toLowerCase()==='detailview'){action='';}
if(!id&&action.toLowerCase()==='editview'){action='create';}
return app.router.buildRoute(module,id,action);},convertToSidecarLink:function(elem){elem=$(elem);var baseUrl=app.config.siteUrl||window.location.pathname;var href=elem.attr('href');var module=this.moduleRegex.exec(href);var dataSidecarRewrite=elem.attr('data-sidecar-rewrite');var action=this.actionRegex.exec(href);if(!_.isArray(module)||_.isEmpty(module[1])||_.isUndefined(app.metadata.getModule(module[1]))||module[1]==="Administration"||href.indexOf("javascript:")===0||dataSidecarRewrite==='false'||(_.isArray(action)&&action[1]==='sugarpdf')){return;}
var sidecarUrl=this.convertToSidecarUrl(href);elem.attr('href',baseUrl+'#'+sidecarUrl);elem.data('sidecarProcessed',true);if(elem.attr('target')==='_blank'){return;}
elem.click(function(e){if(e.button!==0||e.ctrlKey||e.metaKey){return;}
e.stopPropagation();parent.SUGAR.App.router.navigate(sidecarUrl,{trigger:true});return false;});},_rewriteLinksForSidecar:function(frame){var self=this;frame.$('a[href*="module="]').each(function(i,elem){self.convertToSidecarLink(elem);});},_rewriteNewWindowLinks:function(frame){var baseUrl=app.config.siteUrl||window.location.origin+window.location.pathname,$links=frame.$('a[target="_blank"]').not('[href^="http"]').not('[href*="entryPoint=download"]');$links.each(function(i,elem){var $elem=$(elem);if($elem.data('sidecarProcessed')){return;}
$elem.attr('href',baseUrl+'#bwc/'+$elem.attr('href'));});},_dispose:function(){this.bwcModel.off();this.bwcModel=null;app.view.View.prototype._dispose.call(this);}})