<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/EmailAddresses/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_EMAIL_ADDRESS_ID' => 'ID' ,
   'LBL_EMAIL_ADDRESS' => 'E-Posta Adresi' ,
   'LBL_EMAIL_ADDRESS_CAPS' => 'E-Posta Adresi Büyük Harf' ,
   'LBL_INVALID_EMAIL' => 'Geçersiz E-Posta' ,
   'LBL_OPT_OUT' => 'Liste Dışı' ,
   'LBL_DATE_CREATE' => 'Oluşturma Tarihi' ,
   'LBL_DATE_MODIFIED' => 'Değiştirilme Tarihi' ,
   'LBL_DELETED' => 'Sil' );

?>
