//     Zepto.js
(function($){var jsonpID=0,isObject=$.isObject,document=window.document,key,name,rscript=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi;function triggerAndReturn(context,eventName,data){var event=$.Event(eventName);$(context).trigger(event,data);return!event.defaultPrevented;}
function triggerGlobal(settings,context,eventName,data){if(settings.global)return triggerAndReturn(context||document,eventName,data);}
$.active=0;function ajaxStart(settings){if(settings.global&&$.active++===0)triggerGlobal(settings,null,'ajaxStart');}
function ajaxStop(settings){if(settings.global&&!(--$.active))triggerGlobal(settings,null,'ajaxStop');}
function ajaxBeforeSend(xhr,settings){var context=settings.context;if(settings.beforeSend.call(context,xhr,settings)===false||triggerGlobal(settings,context,'ajaxBeforeSend',[xhr,settings])===false)
return false;triggerGlobal(settings,context,'ajaxSend',[xhr,settings]);}
function ajaxSuccess(data,xhr,settings){var context=settings.context,status='success';settings.success.call(context,data,status,xhr);triggerGlobal(settings,context,'ajaxSuccess',[xhr,settings,data]);ajaxComplete(status,xhr,settings);}
function ajaxError(error,type,xhr,settings){var context=settings.context;settings.error.call(context,xhr,type,error);triggerGlobal(settings,context,'ajaxError',[xhr,settings,error]);ajaxComplete(type,xhr,settings);}
function ajaxComplete(status,xhr,settings){var context=settings.context;settings.complete.call(context,xhr,status);triggerGlobal(settings,context,'ajaxComplete',[xhr,settings]);ajaxStop(settings);}
function empty(){}
$.ajaxJSONP=function(options){var callbackName='jsonp'+(++jsonpID),script=document.createElement('script'),abort=function(){$(script).remove();if(callbackName in window)window[callbackName]=empty;ajaxComplete('abort',xhr,options);},xhr={abort:abort},abortTimeout;if(options.error)script.onerror=function(){xhr.abort();options.error();};window[callbackName]=function(data){clearTimeout(abortTimeout);$(script).remove();delete window[callbackName];ajaxSuccess(data,xhr,options);};script.src=options.url.replace(/=\?/,'='+callbackName);$('head').append(script);if(options.timeout>0)abortTimeout=setTimeout(function(){xhr.abort();ajaxComplete('timeout',xhr,options);},options.timeout);return xhr;};$.ajaxSettings={type:'GET',beforeSend:empty,success:empty,error:empty,complete:empty,context:null,global:true,xhr:function(){return new window.XMLHttpRequest();},accepts:{script:'text/javascript, application/javascript',json:'application/json',xml:'application/xml, text/xml',html:'text/html',text:'text/plain'},crossDomain:false,timeout:0};$.ajax=function(options){var settings=$.extend({},options||{});for(key in $.ajaxSettings)if(settings[key]===undefined)settings[key]=$.ajaxSettings[key];ajaxStart(settings);if(!settings.crossDomain)settings.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(settings.url)&&RegExp.$2!=window.location.host;if(/=\?/.test(settings.url))return $.ajaxJSONP(settings);if(!settings.url)settings.url=window.location.toString();if(settings.data&&!settings.contentType)settings.contentType='application/x-www-form-urlencoded';if(isObject(settings.data))settings.data=$.param(settings.data);if(settings.type.match(/get/i)&&settings.data){var queryString=settings.data;if(settings.url.match(/\?.*=/)){queryString='&'+queryString;}else if(queryString[0]!='?'){queryString='?'+queryString;}
settings.url+=queryString;}
var mime=settings.accepts[settings.dataType],baseHeaders={},protocol=/^([\w-]+:)\/\//.test(settings.url)?RegExp.$1:window.location.protocol,xhr=$.ajaxSettings.xhr(),abortTimeout;if(!settings.crossDomain)baseHeaders['X-Requested-With']='XMLHttpRequest';if(mime)baseHeaders['Accept']=mime;settings.headers=$.extend(baseHeaders,settings.headers||{});xhr.onreadystatechange=function(){if(xhr.readyState==4){clearTimeout(abortTimeout);var result,error=false;if((xhr.status>=200&&xhr.status<300)||(xhr.status==0&&protocol=='file:')){if(mime=='application/json'&&!(/^\s*$/.test(xhr.responseText))){try{result=JSON.parse(xhr.responseText);}
catch(e){error=e;}}
else result=xhr.responseText;if(error)ajaxError(error,'parsererror',xhr,settings);else ajaxSuccess(result,xhr,settings);}else{ajaxError(null,'error',xhr,settings);}}};var async='async'in settings?settings.async:true;xhr.open(settings.type,settings.url,async);if(settings.contentType)settings.headers['Content-Type']=settings.contentType;for(name in settings.headers)xhr.setRequestHeader(name,settings.headers[name]);if(ajaxBeforeSend(xhr,settings)===false){xhr.abort();return false;}
if(settings.timeout>0)abortTimeout=setTimeout(function(){xhr.onreadystatechange=empty;xhr.abort();ajaxError(null,'timeout',xhr,settings);},settings.timeout);xhr.send(settings.data);return xhr;};$.get=function(url,success){return $.ajax({url:url,success:success})};$.post=function(url,data,success,dataType){if($.isFunction(data))dataType=dataType||success,success=data,data=null;return $.ajax({type:'POST',url:url,data:data,success:success,dataType:dataType});};$.getJSON=function(url,success){return $.ajax({url:url,success:success,dataType:'json'});};$.fn.load=function(url,success){if(!this.length)return this;var self=this,parts=url.split(/\s/),selector;if(parts.length>1)url=parts[0],selector=parts[1];$.get(url,function(response){self.html(selector?$(document.createElement('div')).html(response.replace(rscript,"")).find(selector).html():response);success&&success.call(self);});return this;};var escape=encodeURIComponent;function serialize(params,obj,traditional,scope){var array=$.isArray(obj);$.each(obj,function(key,value){if(scope)key=traditional?scope:scope+'['+(array?'':key)+']';if(!scope&&array)params.add(value.name,value.value);else if(traditional?$.isArray(value):isObject(value))
serialize(params,value,traditional,key);else params.add(key,value);});}
$.param=function(obj,traditional){var params=[];params.add=function(k,v){this.push(escape(k)+'='+escape(v))};serialize(params,obj,traditional);return params.join('&').replace('%20','+');};})(Zepto);