<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SNIP/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_SNIP_SUMMARY' => 'E-Posta arşivleme, kullanıcıların e-postaları herhangi bir e-posta istemcisi üzerinden, Sugar tarafından sağlanan e-posta adresine göndererek uygulamaya yüklenmesini sağlayan sistemdir. Her Sugar kurulumu, kendisine ait tekil bir e-posta adresi içerir. E-Postaları yüklemek için, kullanıcı e-postayı KIME, BİLGİ veya GİZLİ BİLGİ alanlarını kullanarak bu e-posta adresine gönderir. E-Posta Arşivleme sistemi, e-postayı sugar kurulumuna yükler. Servis, e-postayı bütün ekleri, imajlar ve Takvim olayları ile birlikte yükleyip, e-posta adresi ile eşleştirerek ilgili kayıtları oluşturur. <br><br>
Örnek: Bir kullanıcı olarak bir müşteriyi görüntülediğimde, Müşteri kaydının e-posta adresine göre eşleşen bütün e-postaları görebileceğim. Ayrıca, Müşteri ile ilişkili Kontakların e-postalarını da görebileceğim.<br><br>Aşağıdaki koşulları kabul edin ve hizmeti başlatmak için Etkinleştir butonuna tıklayın. Hizmet etkinleştiğinde, hizmeti kullanmak için gerekli e-posta adresi görünür hale gelecektir.<br><br>' ,
   'LBL_REGISTER_SNIP_FAIL' => 'Arşivlen E-Posta servisiyle bağlantı başarısız: %s!<br>' ,
   'LBL_CONFIGURE_SNIP' => 'E-Posta Arşivleme' ,
   'LBL_DISABLE_SNIP' => 'Etkisizleştirin' ,
   'LBL_SNIP_APPLICATION_UNIQUE_KEY' => 'Uygulama Tekil Anahtarı' ,
   'LBL_SNIP_USER' => 'E-Posta Arşivleyen Kullanıcı' ,
   'LBL_SNIP_PWD' => 'E-Posta Arşivleme Şifresi' ,
   'LBL_SNIP_SUGAR_URL' => 'Sugar Kurulum URL adresi' ,
   'LBL_SNIP_CALLBACK_URL' => 'E-Posta arşivleme servis URL Adresi' ,
   'LBL_SNIP_USER_DESC' => 'E-Posta Arşivleyen Kullanıcı' ,
   'LBL_SNIP_KEY_DESC' => 'E-Posta arşivleme OAuth anahtarı. E-Postaları almak amacıyla bu kuruluma erişmek için kullanılır.' ,
   'LBL_SNIP_STATUS_OK' => 'Etkin' ,
   'LBL_SNIP_STATUS_OK_SUMMARY' => 'Bu Sugar kurulumu başarıyla E-Posta Arşivleme sunucusuna bağlandı.' ,
   'LBL_SNIP_STATUS_ERROR' => 'Hata' ,
   'LBL_SNIP_STATUS_ERROR_SUMMARY' => 'Bu kurulumun geçerli bir e-posta arşivleme sunucu lisansı var fakat sunucu aşağıdaki hata mesajını döndürdü:' ,
   'LBL_SNIP_STATUS_FAIL' => 'E-Posta Arşivleme sunucusuna tanımlama yapılamıyor' ,
   'LBL_SNIP_STATUS_FAIL_SUMMARY' => 'Arşivlenmiş E-Posta servisi şu anda kullanılamaz. Servis arızalı veya Sugar kurulumu ile bağlantı başarısız oldu.' ,
   'LBL_SNIP_GENERIC_ERROR' => 'Arşivlenmiş E-Posta servisi şu anda kullanılamaz. Servis arızalı veya Sugar kurulumu ile bağlantı başarısız oldu.' ,
   'LBL_SNIP_STATUS_RESET' => 'Henüz çalışmadı' ,
   'LBL_SNIP_STATUS_PROBLEM' => 'Problem: %s' ,
   'LBL_SNIP_NEVER' => 'Hiç' ,
   'LBL_SNIP_STATUS_SUMMARY' => 'E-Posta Arşivleme hizmetinin durumu:' ,
   'LBL_SNIP_ACCOUNT' => 'Müşteri' ,
   'LBL_SNIP_STATUS' => 'Durum' ,
   'LBL_SNIP_LAST_SUCCESS' => 'Son başarılı çalışma' ,
   'LBL_SNIP_DESCRIPTION' => 'E-Posta arşivleme servisi otomatik bir e-posta arşivleme sistemidir' ,
   'LBL_SNIP_DESCRIPTION_SUMMARY' => 'E-Postaları manuel olarak yükleme ve bağlamaya gerek kalmadan, SugarCRM içindeki kontaklarınıza gönderilen veya alınan e-postaların görülmesini sağlar' ,
   'LBL_SNIP_PURCHASE_SUMMARY' => 'E-Posta Arşivlemesini kullanmak için bir SugarCRM lisansı satın almanız gerekmektedir' ,
   'LBL_SNIP_PURCHASE' => 'Satın almak için tıklayınız' ,
   'LBL_SNIP_EMAIL' => 'E-Posta Arşivleme Adresi' ,
   'LBL_SNIP_AGREE' => 'Yukarıdaki şartları ve <a href="http://www.sugarcrm.com/crm/TRUSTe/privacy.html" target="_blank">gizlilik sözleşmesini</a> kabul ediyorum.' ,
   'LBL_SNIP_PRIVACY' => 'gizlilik sözleşmesi' ,
   'LBL_SNIP_STATUS_PINGBACK_FAIL' => 'Pingback başarısız' ,
   'LBL_SNIP_STATUS_PINGBACK_FAIL_SUMMARY' => 'E-Posta Arşivleme sunucusu Sugar kurulumun ile bağlantı kuramıyor. Tekrar deneyin veya <a href="http://www.sugarcrm.com/crm/case-tracker/submit.html?lsd=supportportal&tmpl=" target="_blank">müşteri desteğine</a> başvurun.' ,
   'LBL_SNIP_BUTTON_ENABLE' => 'E-Posta Arşivleme Etkinleştir' ,
   'LBL_SNIP_BUTTON_DISABLE' => 'E-Posta Arşivlemeyi Kapat' ,
   'LBL_SNIP_BUTTON_RETRY' => 'Yeniden Bağlanmayı Deneyin' ,
   'LBL_SNIP_ERROR_DISABLING' => 'Arşiv E-posta sunucusuyla iletişim kurmayı denerken bir hata oluştu ve servis devre dışı bırakılamadı' ,
   'LBL_SNIP_ERROR_ENABLING' => 'Arşivlenmiş E-posta sunucusuyla iletişim kurmayı denerken hata oluştu ve servis etkinleştirilemedi' ,
   'LBL_CONTACT_SUPPORT' => 'Lütfen tekrar deneyin veya SugarCRM Destek ile iletişime geçin.' ,
   'LBL_SNIP_SUPPORT' => 'Yardım için SugarCRM Destek birimiyle temasa geçin.' ,
   'ERROR_BAD_RESULT' => 'Servisten kötü cevap döndü' ,
   'ERROR_NO_CURL' => 'cURL uzantıları gerekli, ancak etkinleştirilmemiş' ,
   'ERROR_REQUEST_FAILED' => 'Sunucuya bağlantı kurulamadı' ,
   'LBL_CANCEL_BUTTON_TITLE' => 'İptal' ,
   'LBL_SNIP_MOUSEOVER_STATUS' => 'Sistemin e-posta arşivleme servisinin durumu. Bu durum e-posta arşivleme servisi ile sugar kurulumu arasındaki bağlantının başarılı olup olmadığını gösterir.' ,
   'LBL_SNIP_MOUSEOVER_EMAIL' => 'E-Posta Arşivleme sisteminde kaydedilmesi için gönderilecek e-posta adresidir.' ,
   'LBL_SNIP_MOUSEOVER_SERVICE_URL' => 'Bu URL adresi, E-Posta Arşivleme sunucusuna aittir. E-posta arşivleme sunucusunu etkinleştirmek ve devre dışı bırakmak gibi bütün istekler bu URL üzerinden iletilecektir.' ,
   'LBL_SNIP_MOUSEOVER_INSTANCE_URL' => 'Bu Sugar Kurulumunun web hizmetleri URL adresidir. E-Posta Arşivlenme sunucusu bu URL üzerinden sunucuya bağlanmaktadır.' );

?>
