/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({extendsFrom:'ListView',className:'flex-list-view',_previewed:null,displayFirstNColumns:null,plugins:['Tooltip'],initialize:function(options){app.view.invokeParent(this,{type:'view',name:'list',method:'initialize',args:[options]});this.template=app.template.getView('flex-list');this.events=_.clone(this.events);this.leftColumns=[];this.rightColumns=[];this.addActions();this.visibleFieldsLastStateKey=app.user.lastState.key('visible-fields',this);this._fields=this.parseFields();this.addPreviewEvents();this.resize=_.bind(_.debounce(this.resize,200),this);this.bindResize();if(this.rightColumns.length){this.events=_.extend({},this.events,{'click.right-actions .actions [data-toggle=dropdown]':'delegateDropdown'});}},delegateDropdown:function(e){var $button=this.$(e.currentTarget).first(),$buttonGroup=$button.parents('.btn-group'),menuHeight=$button.height()+$button.next('ul').height(),windowHeight=$(window).height()-65;var needsDropupClass=function(b){return(windowHeight<b.offset().top+menuHeight);};var resetDropdownDelegate=function(){$(this).tooltip('enable');$(this).parents('.main-pane').off('scroll.right-actions');$(this).off('resetDropdownDelegate.right-actions');};this.$('.actions [data-toggle=dropdown]').trigger('resetDropdownDelegate.right-actions');if(!$buttonGroup.hasClass('open')){$button.tooltip('destroy');$button.tooltip('disable');$buttonGroup.toggleClass('dropup',needsDropupClass($button));$button.on('resetDropdownDelegate.right-actions',resetDropdownDelegate);$button.parents('.main-pane').on('scroll.right-actions',_.bind(_.debounce(function(){if(!$buttonGroup.hasClass('open')){$button.off('resetDropdownDelegate.right-actions');return;}
$buttonGroup.toggleClass('dropup',needsDropupClass($button));},30),this));}},addPreviewEvents:function(){this.context.on("list:preview:fire",function(model){app.events.trigger("preview:render",model,this.collection,true);},this);app.events.on("list:preview:decorate",this.decorateRow,this);if(this.layout){this.layout.on("list:sort:fire",function(){app.events.trigger("preview:close");},this);this.layout.on("list:paginate:success",function(){app.events.trigger("preview:collection:change",this.collection);if(this._previewed){this.decorateRow(this._previewed);}},this);}},parseFields:function(){var catalog={'default':[],'available':[],'visible':[],'options':[]};var visibleFieldsLastState=false;if(this.visibleFieldsLastStateKey){visibleFieldsLastState=app.user.lastState.get(this.visibleFieldsLastStateKey);if(!_.isArray(visibleFieldsLastState)||visibleFieldsLastState.length===0){visibleFieldsLastState=false;}}
_.each(this.meta.panels,function(panel){_.each(panel.fields,function(fieldMeta,i){if(_.isNumber(this.displayFirstNColumns)){fieldMeta['default']=(i<this.displayFirstNColumns);panel.fields[i]=fieldMeta;}
var fieldVisible=(fieldMeta['default']!==false);if(fieldVisible){catalog['default'].push(fieldMeta);}
if(visibleFieldsLastState!==false){fieldVisible=(_.indexOf(visibleFieldsLastState,fieldMeta.name)!==-1);}
if(fieldVisible){catalog.visible.push(fieldMeta);}else{catalog.available.push(fieldMeta);}
catalog.options.push(_.extend({selected:fieldVisible},fieldMeta));},this);},this);return catalog;},addActions:function(){var meta=this.meta;if(_.isObject(meta.selection)){switch(meta.selection.type){case'single':this.addSingleSelectionAction();break;case'multi':this.addMultiSelectionAction();break;default:break;}}
if(meta&&_.isObject(meta.rowactions)){this.addRowActions();}},addSingleSelectionAction:function(){var _generateMeta=function(name,label){return{'type':'selection','name':name,'sortable':false,'label':label||''};};var def=this.meta.selection;this.leftColumns.push(_generateMeta(def.name||this.module+'_select',def.label));},addMultiSelectionAction:function(){var _generateMeta=function(buttons,disableSelectAllAlert){return{'type':'fieldset','fields':[{'type':'actionmenu','buttons':buttons||[],'disable_select_all_alert':!!disableSelectAllAlert}],'value':false,'sortable':false};};var buttons=this.meta.selection.actions,disableSelectAllAlert=!!this.meta.selection.disable_select_all_alert;this.leftColumns.push(_generateMeta(buttons,disableSelectAllAlert));},addRowActions:function(){var _generateMeta=function(label,css_class,buttons){return{'type':'fieldset','fields':[{'type':'rowactions','label':label||'','css_class':css_class,'buttons':buttons||[]}],'value':false,'sortable':false};};var def=this.meta.rowactions;this.rightColumns.push(_generateMeta(def.label,def.css_class,def.actions));},decorateRow:function(model){if(_.isUndefined(app.drawer)||app.drawer.isActive(this.$el)){this._previewed=model;this.$("tr.highlighted").removeClass("highlighted current above below");if(model){var rowName=model.module+"_"+model.get("id");var curr=this.$("tr[name='"+rowName+"']");curr.addClass("current highlighted");curr.prev("tr").addClass("highlighted above");curr.next("tr").addClass("highlighted below");}}},_renderHtml:function(ctx,options){this.colSpan=this._fields.visible.length||0;if(this.leftColumns.length){this.colSpan++;}
if(this.rightColumns.length){this.colSpan++;}
if(this.colSpan<2){this.colSpan=null;}
app.view.View.prototype._renderHtml.call(this,ctx,options);if(this.leftColumns.length){this.$el.addClass('left-actions');}
if(this.rightColumns.length){this.$el.addClass('right-actions');}
this.resize();},unbind:function(){$(window).off("resize.flexlist-"+this.cid);app.view.invokeParent(this,{type:'view',name:'list',method:'unbind'});},bindResize:function(){$(window).on("resize.flexlist-"+this.cid,_.bind(this.resize,this));},resize:function(){if(this.disposed){return;}
var $content=this.$('.flex-list-view-content');if(!$content.length){return;}
var toggle=$content.get(0).scrollWidth>$content.width()+1;this.$el.toggleClass('scroll-width',toggle);},_dispose:function(){this.$('.actions [data-toggle=dropdown]').trigger('resetDropdownDelegate.right-actions');this._super('_dispose');}})