/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
({titleSelectedValues:'',titleViewNameTitle:'',toggleTitleTpl:{},scenarioOptions:[],selectedOptions:[],defaultOption:{},defaultSelect2:{},optionsSelect2:{},defaultForecastedAmountKey:'show_worksheet_likely',events:{'click .resetLink':'onResetLinkClicked'},initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.titleViewNameTitle=app.lang.get('LBL_FORECASTS_CONFIG_TITLE_SCENARIOS','Forecasts');this.selectedOptions=[];this.defaultOption={};this.scenarioOptions=[];_.each(options.meta.panels[0].fields,function(field){var obj={id:field.name,text:app.lang.get(field.label,'Forecasts')}
if(field.name==this.defaultForecastedAmountKey){obj['locked']=true;this.defaultOption=obj;}else{this.scenarioOptions.push(obj);}
if(this.context.get('model').get(field.name)==1&&!obj.locked){this.selectedOptions.push(obj);}},this);this.toggleTitleTpl=app.template.getView('forecastsConfigHelpers.toggleTitle','Forecasts');},onResetLinkClicked:function(evt){evt.preventDefault();evt.stopImmediatePropagation();},bindDataChange:function(){if(this.model){this.model.on('change:scenarios',function(model){var arr=[];if(model.get('show_worksheet_likely')){arr.push(app.lang.get('LBL_FORECASTS_CONFIG_WORKSHEET_SCENARIOS_LIKELY','Forecasts'));}
if(model.get('show_worksheet_best')){arr.push(app.lang.get('LBL_FORECASTS_CONFIG_WORKSHEET_SCENARIOS_BEST','Forecasts'));}
if(model.get('show_worksheet_worst')){arr.push(app.lang.get('LBL_FORECASTS_CONFIG_WORKSHEET_SCENARIOS_WORST','Forecasts'));}
this.titleSelectedValues=arr.join(', ');this.updateTitle();},this);this.model.trigger('change:scenarios',this.model);}},updateTitle:function(){var tplVars={title:this.titleViewNameTitle,selectedValues:this.titleSelectedValues,viewName:'forecastsConfigScenarios'};this.$el.find('#'+this.name+'Title').html(this.toggleTitleTpl(tplVars));},_render:function(){app.view.View.prototype._render.call(this);this.$el.addClass('accordion-group');this.updateTitle();this.defaultSelect2=this.$el.find('#scenariosLocked').select2({data:this.defaultOption,multiple:true,dropdownCss:{width:'auto'},dropdownCssClass:'search-related-dropdown',containerCss:"border: none",containerCssClass:'select2-choices-pills-close select2-container-disabled',escapeMarkup:function(m){return m;},initSelection:_.bind(function(element,callback){callback(this.defaultOption);},this)});this.$el.find('.select2-container-disabled').width('auto');this.$el.find('.select2-search-field').css('display','none');this.defaultSelect2.select2('val',this.defaultOption);this.defaultSelect2.select2('disable');this.optionsSelect2=this.$el.find('#scenariosSelect').select2({data:this.scenarioOptions,multiple:true,dropdownCss:{width:"auto"},width:"90%",containerCss:"border: none",containerCssClass:"select2-choices-pills-close",escapeMarkup:function(m){return m;},initSelection:_.bind(function(element,callback){callback(this.selectedOptions);},this)});this.optionsSelect2.select2('val',this.selectedOptions);this.optionsSelect2.on('change',_.bind(this.handleScenarioModelChange,this));},handleScenarioModelChange:function(evt){var changedEnabled=[],changedDisabled=[],allOptions=[];_.each($(evt.target).val().split(','),function(option){changedEnabled.push(option);this.model.set(option,true,{silent:true});},this);_.each(this.scenarioOptions,function(option){allOptions.push(option.id);},this);changedDisabled=_.difference(allOptions,changedEnabled);_.each(changedDisabled,function(option){this.model.set(option,false,{silent:true});},this);this.model.trigger('change:scenarios',this.model);},formatCustomSelection:function(item){return'<a class="select2-choice-filter" rel="'+item.id+'" href="javascript:void(0)">'+item.text+'</a>';},_dispose:function(){this.defaultSelect2.off();this.defaultSelect2.select2('destroy');this.defaultSelect2=null;this.optionsSelect2.off();this.optionsSelect2.select2('destroy');this.optionsSelect2=null;app.view.Component.prototype._dispose.call(this);}})