nv.models.gaugeChart=function(){var gauge=nv.models.gauge(),legend=nv.models.legend();var margin={top:30,right:20,bottom:20,left:20},width=null,height=null,showLegend=true,showTitle=false,tooltip=null,tooltips=true,tooltipContent=function(key,y,e,graph){return'<h3>'+key+'</h3>'+'<p>'+y+'</p>';},x,y,noData="No Data Available.",dispatch=d3.dispatch('tooltipShow','tooltipHide','tooltipMove');var showTooltip=function(e,offsetElement){var left=e.pos[0],top=e.pos[1],y=gauge.valueFormat()((e.point.y1-e.point.y0)),content=tooltipContent(e.point.key,y,e,chart);tooltip=nv.tooltip.show([left,top],content,e.value<0?'n':'s',null,offsetElement);};function chart(selection){selection.each(function(chartData){var properties=chartData.properties,data=chartData.data;var container=d3.select(this),that=this;var availableWidth=(width||parseInt(container.style('width'),10)||960)
-margin.left-margin.right,availableHeight=(height||parseInt(container.style('height'),10)||400)
-margin.top-margin.bottom;chart.update=function(){container.transition().duration(300).call(chart);};chart.container=this;if(!data||!data.length){var noDataText=container.selectAll('.nv-noData').data([noData]);noDataText.enter().append('text').attr('class','nvd3 nv-noData').attr('dy','-.7em').style('text-anchor','middle');noDataText.attr('x',margin.left+availableWidth / 2).attr('y',margin.top+availableHeight / 2).text(function(d){return d});return chart;}else{container.selectAll('.nv-noData').remove();}
var wrap=container.selectAll('g.nv-wrap.nv-gaugeChart').data([data]);var gEnter=wrap.enter().append('g').attr('class','nvd3 nv-wrap nv-gaugeChart').append('g');var g=wrap.select('g');gEnter.append('g').attr('class','nv-gaugeWrap');var titleHeight=0,legendHeight=0;if(showLegend)
{gEnter.append('g').attr('class','nv-legendWrap');legend.width(availableWidth).key(gauge.x());g.select('.nv-legendWrap').datum(data).call(legend);legendHeight=legend.height();if(margin.top!==legendHeight+titleHeight){margin.top=legendHeight+titleHeight;availableHeight=(height||parseInt(container.style('height'),10)||400)
-margin.top-margin.bottom;}
g.select('.nv-legendWrap').attr('transform','translate(0,'+(-margin.top)+')');}
if(showTitle&&properties.title)
{gEnter.append('g').attr('class','nv-titleWrap');g.select('.nv-title').remove();g.select('.nv-titleWrap').append('text').attr('class','nv-title').attr('x',0).attr('y',0).attr('text-anchor','start').text(properties.title).attr('stroke','none').attr('fill','black');titleHeight=parseInt(g.select('.nv-title').node().getBBox().height,10)+
parseInt(g.select('.nv-title').style('margin-top'),10)+
parseInt(g.select('.nv-title').style('margin-bottom'),10);if(margin.top!==titleHeight+legendHeight)
{margin.top=titleHeight+legendHeight;availableHeight=(height||parseInt(container.style('height'),10)||400)
-margin.top-margin.bottom;}
g.select('.nv-titleWrap').attr('transform','translate(0,'+(-margin.top+parseInt(g.select('.nv-title').node().getBBox().height,10))+')');}
wrap.attr('transform','translate('+margin.left+','+margin.top+')');gauge.width(availableWidth).height(availableHeight);var gaugeWrap=g.select('.nv-gaugeWrap').datum(chartData);gaugeWrap.transition().call(gauge);dispatch.on('tooltipShow',function(e){if(tooltips){showTooltip(e);}});});return chart;}
gauge.dispatch.on('elementMouseover.tooltip',function(e){e.pos=[e.pos[0]+margin.left,e.pos[1]+margin.top];dispatch.tooltipShow(e);});gauge.dispatch.on('elementMouseout.tooltip',function(e){dispatch.tooltipHide(e);});dispatch.on('tooltipHide',function(){if(tooltips)nv.tooltip.cleanup();});gauge.dispatch.on('elementMousemove',function(e){dispatch.tooltipMove(e);});dispatch.on('tooltipMove',function(e){if(tooltip){nv.tooltip.position(tooltip,e.pos);}});chart.dispatch=dispatch;chart.legend=legend;chart.gauge=gauge;d3.rebind(chart,gauge,'valueFormat','values','x','y','id','showLabels','setPointer','ringWidth','labelThreshold','maxValue','minValue','transitionMs','color','fill','classes','gradient');chart.colorData=function(_){var colors=function(d,i){return nv.utils.defaultColor()(d,i);},classes=function(d,i){return'nv-group nv-series-'+i;},type=arguments[0],params=arguments[1]||{};switch(type){case'graduated':var c1=params.c1,c2=params.c2,l=params.l;colors=function(d,i){return d3.interpolateHsl(d3.rgb(c1),d3.rgb(c2))(i/l);};break;case'class':colors=function(){return'inherit';};classes=function(d,i){var iClass=(i*(params.step||1))%20;return'nv-group nv-series-'+i+' '+(d.classes||'nv-fill'+(iClass>9?'':'0')+iClass);};break;}
var fill=(!params.gradient)?colors:function(d,i){return gauge.gradient(d,i);};gauge.color(colors);gauge.fill(fill);gauge.classes(classes);legend.color(colors);legend.classes(classes);return chart;};chart.margin=function(_){if(!arguments.length)return margin;margin=_;return chart;};chart.width=function(_){if(!arguments.length)return width;width=_;return chart;};chart.height=function(_){if(!arguments.length)return height;height=_;return chart;};chart.showLegend=function(_){if(!arguments.length)return showLegend;showLegend=_;return chart;};chart.showTitle=function(_){if(!arguments.length)return showTitle;showTitle=_;return chart;};chart.tooltip=function(_){if(!arguments.length)return tooltip;tooltip=_;return chart;};chart.tooltips=function(_){if(!arguments.length)return tooltips;tooltips=_;return chart;};chart.tooltipContent=function(_){if(!arguments.length)return tooltipContent;tooltipContent=_;return chart;};chart.noData=function(_){if(!arguments.length)return noData;noData=_;return chart;};return chart;}