nv.models.stackedAreaChart=function(){var stacked=nv.models.stackedArea(),xAxis=nv.models.axis(),yAxis=nv.models.axis(),legend=nv.models.legend(),controls=nv.models.legend();var margin={top:30,right:25,bottom:50,left:60},width=null,height=null,showControls=false,showLegend=true,showTitle=false,tooltip=null,tooltips=true,tooltipContent=function(key,x,y,e,graph){return'<h3>'+key+'</h3>'+'<p>'+y+' on '+x+'</p>';},x,y,yAxisTickFormat=d3.format(',.2f'),state={style:stacked.style()},noData='No Data Available.',dispatch=d3.dispatch('tooltipShow','tooltipHide','tooltipMove','stateChange','changeState');xAxis.orient('bottom').tickPadding(7);yAxis.orient('left');stacked.scatter.pointActive(function(d){return!!Math.round(stacked.y()(d)*100);});var showTooltip=function(e,offsetElement){var left=e.pos[0]+(offsetElement.offsetLeft||0),top=e.pos[1]+(offsetElement.offsetTop||0),x=xAxis.tickFormat()(stacked.x()(e.point,e.pointIndex)),y=yAxis.tickFormat()(stacked.y()(e.point,e.pointIndex)),content=tooltipContent(e.series.key,x,y,e,chart);tooltip=nv.tooltip.show([left,top],content,null,null,offsetElement);};function chart(selection){selection.each(function(chartData){var properties=chartData.properties,data=chartData.data;var container=d3.select(this),that=this;var availableWidth=(width||parseInt(container.style('width'),10)||960)
-margin.left-margin.right,availableHeight=(height||parseInt(container.style('height'),10)||400)
-margin.top-margin.bottom;chart.update=function(){container.transition().duration(300).call(chart);};chart.container=this;state.disabled=data.map(function(d){return!!d.disabled});if(!data||!data.length||!data.filter(function(d){return d.values.length}).length){var noDataText=container.selectAll('.nv-noData').data([noData]);noDataText.enter().append('text').attr('class','nvd3 nv-noData').attr('dy','-.7em').style('text-anchor','middle');noDataText.attr('x',margin.left+availableWidth / 2).attr('y',margin.top+availableHeight / 2).text(function(d){return d});return chart;}else{container.selectAll('.nv-noData').remove();}
x=stacked.xScale();y=stacked.yScale();var wrap=container.selectAll('g.nv-wrap.nv-stackedAreaChart').data([data]);var gEnter=wrap.enter().append('g').attr('class','nvd3 nv-wrap nv-stackedAreaChart').append('g');var g=wrap.select('g');gEnter.append('g').attr('class','nv-x nv-axis');gEnter.append('g').attr('class','nv-y nv-axis');gEnter.append('g').attr('class','nv-stackedWrap');var titleHeight=0,legendHeight=0;if(showLegend){gEnter.append('g').attr('class','nv-legendWrap');legend.width(availableWidth*(showControls?0.7:1));g.select('.nv-legendWrap').datum(data).call(legend);legendHeight=legend.height();if(margin.top!==legendHeight+titleHeight){margin.top=legendHeight+titleHeight;availableHeight=(height||parseInt(container.style('height'),10)||400)
-margin.top-margin.bottom;}
g.select('.nv-legendWrap').attr('transform','translate('+(availableWidth*(showControls?0.3:0))+','+(-margin.top)+')');}
if(showTitle&&properties.title){gEnter.append('g').attr('class','nv-titleWrap');g.select('.nv-title').remove();g.select('.nv-titleWrap').append('text').attr('class','nv-title').attr('x',0).attr('y',0).attr('text-anchor','start').text(properties.title).attr('stroke','none').attr('fill','black');titleHeight=parseInt(g.select('.nv-title').node().getBBox().height,10)+
parseInt(g.select('.nv-title').style('margin-top'),10)+
parseInt(g.select('.nv-title').style('margin-bottom'),10);if(margin.top!==titleHeight+legendHeight)
{margin.top=titleHeight+legendHeight;availableHeight=(height||parseInt(container.style('height'),10)||400)
-margin.top-margin.bottom;}
g.select('.nv-titleWrap').attr('transform','translate(0,'+(-margin.top+parseInt(g.select('.nv-title').node().getBBox().height,10))+')');}
if(showControls){var controlsData=[{key:'Stacked',disabled:stacked.offset()!='zero'},{key:'Stream',disabled:stacked.offset()!='wiggle'},{key:'Expanded',disabled:stacked.offset()!='expand'}];gEnter.append('g').attr('class','nv-controlsWrap');controls.width(availableWidth*0.3).color(['#444']);g.select('.nv-controlsWrap').datum(controlsData).attr('transform','translate(0,'+(-margin.top+titleHeight)+')').call(controls);}
wrap.attr('transform','translate('+margin.left+','+margin.top+')');stacked.width(availableWidth).height(availableHeight);var stackedWrap=g.select('.nv-stackedWrap').datum(data);stackedWrap.transition().call(stacked);xAxis.scale(x).ticks(availableWidth / 100).tickSize(-availableHeight,0);g.select('.nv-x.nv-axis').attr('transform','translate(0,'+availableHeight+')');g.select('.nv-x.nv-axis').transition().call(xAxis);yAxis.scale(y).ticks(stacked.offset()=='wiggle'?0:availableHeight / 36).tickSize(-availableWidth,0).setTickFormat(stacked.offset()=='expand'?d3.format('%'):yAxisTickFormat);g.select('.nv-y.nv-axis').transition().call(yAxis);stacked.dispatch.on('areaClick.toggle',function(e){if(data.filter(function(d){return!d.disabled;}).length===1)
data=data.map(function(d){d.disabled=false;return d;});else
data=data.map(function(d,i){d.disabled=(i!=e.seriesIndex);return d;});state.disabled=data.map(function(d){return!!d.disabled;});dispatch.stateChange(state);container.transition().duration(300).call(chart);});legend.dispatch.on('legendClick',function(d,i){d.disabled=!d.disabled;if(!data.filter(function(d){return!d.disabled;}).length){data.map(function(d){d.disabled=false;return d;});}
state.disabled=data.map(function(d){return!!d.disabled});dispatch.stateChange(state);container.transition().duration(300).call(chart);});controls.dispatch.on('legendClick',function(d,i){if(!d.disabled)return;controlsData=controlsData.map(function(s){s.disabled=true;return s;});d.disabled=false;switch(d.key){case'Stacked':stacked.style('stack');break;case'Stream':stacked.style('stream');break;case'Expanded':stacked.style('expand');break;}
state.style=stacked.style();dispatch.stateChange(state);container.transition().duration(300).call(chart);});dispatch.on('tooltipShow',function(e){if(tooltips){showTooltip(e,that.parentNode);}});dispatch.on('changeState',function(e){if(typeof e.disabled!=='undefined'){data.forEach(function(series,i){series.disabled=e.disabled[i];});state.disabled=e.disabled;}
if(typeof e.style!=='undefined'){stacked.style(e.style);}
container.call(chart);});});return chart;}
stacked.dispatch.on('tooltipShow',function(e){dispatch.tooltipShow(e);});stacked.dispatch.on('tooltipHide',function(e){dispatch.tooltipHide(e);});stacked.dispatch.on('areaMouseover.tooltip',function(e){dispatch.tooltipShow(e);});stacked.dispatch.on('areaMouseout.tooltip',function(e){dispatch.tooltipHide(e);});dispatch.on('tooltipHide',function(){if(tooltips){nv.tooltip.cleanup();}});stacked.dispatch.on('areaMousemove.tooltip',function(e){dispatch.tooltipMove(e);});dispatch.on('tooltipMove',function(e){if(tooltip){nv.tooltip.position(tooltip,e.pos);}});chart.dispatch=dispatch;chart.stacked=stacked;chart.legend=legend;chart.controls=controls;chart.xAxis=xAxis;chart.yAxis=yAxis;d3.rebind(chart,stacked,'x','y','size','xScale','yScale','xDomain','yDomain','sizeDomain','interactive','offset','order','style','clipEdge','forceX','forceY','forceSize','color','fill','classes','gradient');chart.colorData=function(_){var colors=function(d,i){return nv.utils.defaultColor()(d,i);},classes=function(d,i){return'nv-area nv-area-'+i;},type=arguments[0],params=arguments[1]||{};switch(type){case'graduated':var c1=params.c1,c2=params.c2,l=params.l;colors=function(d,i){return d3.interpolateHsl(d3.rgb(c1),d3.rgb(c2))(i/l);};break;case'class':colors=function(){return'inherit';};classes=function(d,i){var iClass=(i*(params.step||1))%20;return'nv-area nv-area-'+i+' '+(d.classes||'nv-fill'+(iClass>9?'':'0')+iClass+' nv-stroke'+i);};break;}
var fill=(!params.gradient)?colors:function(d,i){var p={orientation:params.orientation||'horizontal',position:params.position||'base'};return stacked.gradient(d,i,p);};stacked.color(colors);stacked.fill(fill);stacked.classes(classes);legend.color(colors);legend.classes(classes);return chart;};chart.margin=function(_){if(!arguments.length)return margin;margin.top=typeof _.top!='undefined'?_.top:margin.top;margin.right=typeof _.right!='undefined'?_.right:margin.right;margin.bottom=typeof _.bottom!='undefined'?_.bottom:margin.bottom;margin.left=typeof _.left!='undefined'?_.left:margin.left;return chart;};chart.width=function(_){if(!arguments.length)return width;width=_;return chart;};chart.height=function(_){if(!arguments.length)return height;height=_;return chart;};chart.showControls=function(_){if(!arguments.length)return showControls;showControls=_;return chart;};chart.showLegend=function(_){if(!arguments.length)return showLegend;showLegend=_;return chart;};chart.showTitle=function(_){if(!arguments.length)return showTitle;showTitle=_;return chart;};chart.tooltip=function(_){if(!arguments.length)return tooltip;tooltip=_;return chart;};chart.tooltips=function(_){if(!arguments.length)return tooltips;tooltips=_;return chart;};chart.tooltipContent=function(_){if(!arguments.length)return tooltipContent;tooltipContent=_;return chart;};chart.state=function(_){if(!arguments.length)return state;state=_;return chart;};chart.noData=function(_){if(!arguments.length)return noData;noData=_;return chart;};yAxis.setTickFormat=yAxis.tickFormat;yAxis.tickFormat=function(_){if(!arguments.length)return yAxisTickFormat;yAxisTickFormat=_;return yAxis;};return chart;}