nv.models.treemapChart=function(){var treemap=nv.models.treemap(),legend=nv.models.legend();var margin={top:0,right:10,bottom:10,left:10},width=null,height=null,showTitle=false,showLegend=false,tooltip=null,tooltips=true,tooltipContent=function(point){var tt='<p>Value: <b>'+d3.format(',.2s')(point.value)+'</b></p>'+'<p>Name: <b>'+point.name+'</b></p>';return tt;},colorArray=d3.scale.category20().range().map(function(d){return d;}),x,y,noData='No Data Available.',dispatch=d3.dispatch('tooltipShow','tooltipHide','tooltipMove','elementMousemove');var showTooltip=function(e,offsetElement){var left=e.pos[0],top=e.pos[1],content=tooltipContent(e.point);tooltip=nv.tooltip.show([left,top],content,null,null,offsetElement);};function chart(selection){selection.each(function(chartData){var data=[chartData];var container=d3.select(this),that=this;var availableWidth=(width||parseInt(container.style('width'),10)||960)-margin.left-margin.right,availableHeight=(height||parseInt(container.style('height'),10)||400)-margin.top-margin.bottom;chart.update=function(){container.transition().duration(300).call(chart);};chart.container=this;if(!data||!data.length||!data.filter(function(d){return d.children.length;}).length){var noDataText=container.selectAll('.nv-noData').data([noData]);noDataText.enter().append('text').attr('class','nvd3 nv-noData').attr('dy','-.7em').style('text-anchor','middle');noDataText.attr('x',margin.left+availableWidth / 2).attr('y',margin.top+availableHeight / 2).text(function(d){return d;});return chart;}else{container.selectAll('.nv-noData').remove();}
if(colorData==='data'){removeColors(data[0]);}
var wrap=container.selectAll('g.nv-wrap.nv-treemapWithLegend').data(data);var gEnter=wrap.enter().append('g').attr('class','nvd3 nv-wrap nv-treemapWithLegend').append('g');var g=wrap.select('g');gEnter.append('g').attr('class','nv-treemapWrap');var titleHeight=0,legendHeight=0;if(showLegend){gEnter.append('g').attr('class','nv-legendWrap');legend.width(availableWidth+margin.left);g.select('.nv-legendWrap').datum(data).call(legend);legendHeight=legend.height()+10;if(margin.top!==legendHeight+titleHeight){margin.top=legendHeight+titleHeight;availableHeight=(height||parseInt(container.style('height'),10)||400)-margin.top-margin.bottom;}
g.select('.nv-legendWrap').attr('transform','translate('+(-margin.left)+','+(-margin.top)+')');}
if(showTitle&&properties.title){gEnter.append('g').attr('class','nv-titleWrap');g.select('.nv-title').remove();g.select('.nv-titleWrap').append('text').attr('class','nv-title').attr('x',0).attr('y',0).attr('text-anchor','start').text(properties.title).attr('stroke','none').attr('fill','black');titleHeight=parseInt(g.select('.nv-title').style('height'),10)+
parseInt(g.select('.nv-title').style('margin-top'),10)+
parseInt(g.select('.nv-title').style('margin-bottom'),10);if(margin.top!==titleHeight+legendHeight){margin.top=titleHeight+legendHeight;availableHeight=(height||parseInt(container.style('height'),10)||400)-margin.top-margin.bottom;}
g.select('.nv-titleWrap').attr('transform','translate(0,'+(-margin.top+parseInt(g.select('.nv-title').style('height'),10))+')');}
wrap.attr('transform','translate('+margin.left+','+margin.top+')');treemap.width(availableWidth).height(availableHeight);var treemapWrap=g.select('.nv-treemapWrap').datum(data.filter(function(d){return!d.disabled;}));treemapWrap.transition().call(treemap);legend.dispatch.on('legendClick',function(d,i){d.disabled=!d.disabled;if(!data.filter(function(d){return!d.disabled;}).length){data.map(function(d){d.disabled=false;wrap.selectAll('.nv-series').classed('disabled',false);return d;});}
container.transition().duration(300).call(chart);});dispatch.on('tooltipShow',function(e){if(tooltips){showTooltip(e,that.parentNode);}});function removeColors(d){var i,l;if(d.color&&colorArray.indexOf(d.color)!==-1){colorArray.splice(colorArray.indexOf(d.color),1);}
if(d.children)
{l=d.children.length;for(i=0;i<l;i+=1){removeColors(d.children[i]);}}}});return chart;}
treemap.dispatch.on('elementMouseover',function(e){e.pos=[e.pos[0]+margin.left,e.pos[1]+margin.top];dispatch.tooltipShow(e);});treemap.dispatch.on('elementMouseout',function(e){dispatch.tooltipHide(e);});dispatch.on('tooltipHide',function(){if(tooltips){nv.tooltip.cleanup();}});treemap.dispatch.on('elementMousemove',function(e){dispatch.tooltipMove(e);});dispatch.on('tooltipMove',function(e){if(tooltip){nv.tooltip.position(tooltip,e.pos);}});chart.dispatch=dispatch;chart.legend=legend;chart.treemap=treemap;d3.rebind(chart,treemap,'x','y','xDomain','yDomain','forceX','forceY','clipEdge','id','delay','leafClick','getSize','getName','groups','color','fill','classes','gradient');chart.colorData=function(_){if(!arguments.length){return colorData;}
var type=arguments[0],params=arguments[1]||{},colors=function(d,i){var c=(type==='data'&&d.color)?{color:d.color}:{};return nv.utils.getColor(colorArray)(c,i);},classes=function(d,i){return'nv-child';};switch(type){case'graduated':colors=function(d,i,l){return d3.interpolateHsl(d3.rgb(params.c1),d3.rgb(params.c2))(i/l);};break;case'class':colors=function(){return'inherit';};classes=function(d,i){var iClass=(i*(params.step||1))%20;return'nv-child '+(d.className||'nv-fill'+(iClass>9?'':'0')+iClass);};break;}
var fill=(!params.gradient)?colors:function(d,i){var p={orientation:params.orientation||'horizontal',position:params.position||'base'};return treemap.gradient(d,i,p);};treemap.color(colors);treemap.fill(fill);treemap.classes(classes);legend.color(colors);legend.classes(classes);colorData=arguments[0];return chart;};chart.x=function(_){if(!arguments.length){return getX;}
getX=_;treemap.x(_);return chart;};chart.y=function(_){if(!arguments.length){return getY;}
getY=_;treemap.y(_);return chart;};chart.margin=function(_){if(!arguments.length){return margin;}
margin.top=typeof _.top!=='undefined'?_.top:margin.top;margin.right=typeof _.right!=='undefined'?_.right:margin.right;margin.bottom=typeof _.bottom!=='undefined'?_.bottom:margin.bottom;margin.left=typeof _.left!=='undefined'?_.left:margin.left;return chart;};chart.width=function(_){if(!arguments.length){return width;}
width=_;return chart;};chart.height=function(_){if(!arguments.length){return height;}
height=_;return chart;};chart.showTitle=function(_){if(!arguments.length){return showTitle;}
showTitle=_;return chart;};chart.showLegend=function(_){if(!arguments.length){return showLegend;}
showLegend=_;return chart;};chart.tooltip=function(_){if(!arguments.length)return tooltip;tooltip=_;return chart;};chart.tooltips=function(_){if(!arguments.length){return tooltips;}
tooltips=_;return chart;};chart.tooltipContent=function(_){if(!arguments.length){return tooltipContent;}
tooltipContent=_;return chart;};chart.noData=function(_){if(!arguments.length){return noData;}
noData=_;return chart;};return chart;};