/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
({events:{'click a[name="cancel_button"]':'onButtonClicked','click a[name="save_button"]':'onButtonClicked'},initialize:function(options){app.view.View.prototype.initialize.call(this,options);var model=this.context.get('model');model.url=app.api.buildURL("Forecasts","config");model.sync=function(method,model,options){this.trigger("data:sync:start",method,model,options);var url=_.isFunction(model.url)?model.url():model.url;return app.api.call(method,url,model,options);};model.fetch=function(options){options=options?_.clone(options):{};if(options.parse===void 0)options.parse=true;var model=this;var success=options.success;options.success=function(resp){if(!model.set(model.parse(resp,options),options))return false;if(success)success(model,resp,options);model.trigger('sync',model,resp,options);};var error=options.error;options.error=function(resp){if(error)error(model,resp,options);model.trigger('error',model,resp,options);};return this.sync('read',this,options);};model.save=function(key,val,options){var attrs,method,xhr,attributes=this.attributes;if(key==null||typeof key==='object'){attrs=key;options=val;}else{(attrs={})[key]=val;}
if(attrs&&(!options||!options.wait)&&!this.set(attrs,options))return false;options=_.extend({validate:true},options);if(!this._validate(attrs,options))return false;if(attrs&&options.wait){this.attributes=_.extend({},attributes,attrs);}
if(options.parse===void 0)options.parse=true;var model=this;var success=options.success;options.success=function(resp){model.attributes=attributes;var serverAttrs=model.parse(resp,options);if(options.wait)serverAttrs=_.extend(attrs||{},serverAttrs);if(_.isObject(serverAttrs)&&!model.set(serverAttrs,options)){return false;}
if(success)success(model,resp,options);model.trigger('sync',model,resp,options);};method=this.isNew()?'create':(options.patch?'patch':'update');if(method==='patch')options.attrs=attrs;xhr=this.sync(method,this,options);if(attrs&&options.wait)this.attributes=attributes;return xhr;}
this.context.set({model:model});},onButtonClicked:function(evt){var btnName=$(evt.target).attr('name').slice(0,-7);switch(btnName){case'cancel':this.cancelConfig();break;case'save':this.saveConfig();break;}},saveConfig:function(){var firstTime=false;this.context.get('model').set({is_setup:true,show_forecasts_commit_warnings:true});if(this.context.get('model').get('first_time')!=undefined){this.context.get('model').unset('first_time');firstTime=true;}
var mdl=this.context.get('model');if(mdl.get('forecast_ranges')=="show_custom_buckets"){var ranges=mdl.get('show_custom_buckets_ranges'),commitStages=[];mdl.unset('commit_stages_included');_.each(ranges,function(range,key){if(range.in_included_total){commitStages.push(key)}
delete range.in_included_total;},this);mdl.set({commit_stages_included:commitStages,show_custom_buckets_ranges:ranges});}
this.context.get('model').save({},{success:_.bind(function(model){if(app.drawer&&!firstTime){this.showSavedConfirmation();app.drawer.close(this.context,this.context.get('model'));}else{app.drawer.close(this.context,this.context.get('model'));if(app.controller.context.get("module")=="Forecasts"){this.showSavedConfirmation(function(){window.location='#Forecasts';window.location.reload();});}else{this.showSavedConfirmation();}}},this)});},showSavedConfirmation:function(onClose){onClose=onClose||function(){};var alert=app.alert.show('forecasts_config_success',{level:'success',title:app.lang.get('LBL_FORECASTS_CONFIG_TITLE_FORECAST_SETTINGS','Forecasts')+':',messages:app.lang.get('LBL_FORECASTS_CONFIG_SETTINGS_SAVED','Forecasts'),autoClose:true,onAutoClose:_.bind(function(){alert.getCloseSelector().off();onClose();})});alert.getCloseSelector().on('click',onClose);},cancelConfig:function(){if(app.drawer){app.drawer.close(this.context,this.context.get('model'));}
if(this.context.get('model').get('is_setup')==0){if(app.controller.context.get('module')=='Forecasts'){app.router.goBack();}}}})