/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({extendsFrom:'ListView',plugins:['Dashlet'],_defaultSettings:{limit:5,my_items:'1',favorites:'0'},moduleBlacklist:['Home'],_availableModules:{},_availableColumns:{},initialize:function(options){options.meta=_.extend({},options.meta,{last_state:{id:'dashable-list'}});this._super('initialize',[options]);},initDashlet:function(view){if(this.meta.config){this.settings.on('change:module',function(model,moduleName){var label=(model.get('my_items')=='1')?'TPL_DASHLET_MY_MODULE':'LBL_MODULE_NAME';model.set('label',app.lang.get(label,moduleName,{module:moduleName}));this._updateDisplayColumns();},this);}
this._initializeSettings();if(this.meta.config){this._configureDashlet();}else{this._displayDashlet();}},getLabel:function(){var module=this.settings.get('module')||this.context.get('module');return app.lang.get(this.settings.get('label'),module,{module:module});},_initializeSettings:function(){if(!this.settings.get('limit')){this.settings.set('limit',this._defaultSettings.limit);}
if(!this.settings.get('my_items')){this.settings.set('my_items',this._defaultSettings.my_items);}
if(!this.settings.get('favorites')){this.settings.set('favorites',this._defaultSettings.favorites);}
this._setDefaultModule();if(!this.settings.get('label')){this.settings.set('label','LBL_MODULE_NAME');}},_setDefaultModule:function(){var availableModules=_.keys(this._getAvailableModules()),definedModule=this.settings.get('module'),module=definedModule||this.context.get('module');if(!_.contains(availableModules,module)){module=_.first(availableModules);}
if(definedModule!==module){this.settings.set('module',module);}},_updateDisplayColumns:function(){var availableColumns=this._getAvailableColumns(),columnsFieldName='display_columns',columnsField=this.getField(columnsFieldName);if(columnsField){columnsField.items=availableColumns;}
this.settings.set(columnsFieldName,_.keys(availableColumns));},_configureDashlet:function(){var availableModules=this._getAvailableModules(),availableColumns=this._getAvailableColumns();_.each(this.getFieldMetaForView(this.meta),function(field){switch(field.name){case'module':field.options=availableModules;break;case'display_columns':field.options=availableColumns;break;}});},_getAvailableModules:function(){if(_.isEmpty(this._availableModules)||!_.isObject(this._availableModules)){this._availableModules={};var allowedModules=_.difference(app.user.get('module_list'),this.moduleBlacklist);_.each(allowedModules,function(module){var hasListView=!_.isEmpty(this.getFieldMetaForView(app.metadata.getView(module,'list')));if(hasListView){this._availableModules[module]=app.lang.get('LBL_MODULE_NAME',module);}},this);}
return this._availableModules;},_getListMeta:function(module){var listMeta;if(app.metadata.getModule(module).isBwcEnabled){listMeta=app.bwc.getLegacyMetadata(module,'listviewdefs');}else{listMeta=app.metadata.getView(module,'list');}
return listMeta;},_getAvailableColumns:function(){var columns={},module=this.settings.get('module');if(!module){return columns;}
if(!_.isEmpty(this._availableColumns[module])){return this._availableColumns[module];}
_.each(this.getFieldMetaForView(this._getListMeta(module)),function(field){columns[field.name]=app.lang.get(field.label||field.name,module);});this._availableColumns[module]=columns;return columns;},_displayDashlet:function(){this.context.set('skipFetch',false);this.context.set('limit',this.settings.get('limit'));this._intializeFilter();var columns=this._getColumnsForDisplay();this.meta.panels=[{fields:columns}];this._startAutoRefresh();},_intializeFilter:function(){var filter=[];if(this.settings.get('my_items')==='1'){filter.push({'$owner':''});}
if(this.settings.get('favorites')==='1'){filter.push({'$favorite':''});}
this.context.get('collection').filterDef=(filter.length>1)?{'$and':filter}:filter;},_getColumnsForDisplay:function(){var columns=[],fields=this.getFieldMetaForView(this._getListMeta(this.settings.get('module')));if(!this.settings.get('display_columns')){this._updateDisplayColumns();}
_.each(this.settings.get('display_columns'),function(name){var field=_.find(fields,function(field){return field.name===name;},this);var column=_.extend({name:name,sortable:true},field||{});columns.push(column);},this);return columns;},_startAutoRefresh:function(){var refreshRate=parseInt(this.settings.get('auto_refresh'),10);if(refreshRate){this._stopAutoRefresh();this._timerId=setInterval(_.bind(function(){this.context.resetLoadFlag();this.layout.loadData();},this),refreshRate*1000*60);}},_stopAutoRefresh:function(){if(this._timerId){clearInterval(this._timerId);}},_dispose:function(){this._stopAutoRefresh();this._super('_dispose');},getFieldMetaForView:function(meta){meta=_.isObject(meta)?meta:{};return!_.isUndefined(meta.panels)?_.flatten(_.pluck(meta.panels,'fields')):[];}})