/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement ("MSA"), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({plugins:['Dashlet','Timeago'],events:{'click [data-action=show-more]':'showMore','click [data-action=tab-switcher]':'tabSwitcher','click [data-action=visibility-switcher]':'visibilitySwitcher'},initDashlet:function(){if(this.meta.config){return;}
this.collection=new Backbone.Collection();this._initMaxHeightTarget();this._initEvents();this._initTabs();this._initTemplates();},_initMaxHeightTarget:function(){this.maxHeightTarget=this.meta.max_height_target||'div.tab-content';return this;},_initEvents:function(){this.settings.on('change:filter',this.loadData,this);return this;},_initTabs:function(){this.tabs=[];_.each(this.dashletConfig.tabs,function(tab,index){if(tab.active){this.settings.set('activeTab',index);}
var collection=this._createCollection(tab);if(_.isNull(collection)){return;}
this.tabs[index]=tab;this.tabs[index].collection=collection;this.tabs[index].relate=_.isObject(collection.link);this.tabs[index].record_date=tab.record_date||'date_entered';if(tab.include_child_items){this.tabs[index].include_child_items=this.module==='Accounts'&&_.contains(['Calls','Meetings'],tab.module);}},this);return this;},_initTemplates:function(){this._tabsTpl=app.template.getView(this.name+'.tabs',this.module)||app.template.getView(this.name+'.tabs')||app.template.getView('tabbed-dashlet.tabs',this.module)||app.template.getView('tabbed-dashlet.tabs');this._toolbarTpl=app.template.getView(this.name+'.toolbar',this.module)||app.template.getView(this.name+'.toolbar')||app.template.getView('tabbed-dashlet.toolbar',this.module)||app.template.getView('tabbed-dashlet.toolbar');return this;},_getRecordsTemplate:function(module){this._recordsTpl=this._recordsTpl||{};if(!this._recordsTpl[module]){this._recordsTpl[module]=app.template.getView(this.name+'.records',module)||app.template.getView(this.name+'.records',this.module)||app.template.getView(this.name+'.records')||app.template.getView('tabbed-dashlet.records',this.module)||app.template.getView('tabbed-dashlet.records');}
return this._recordsTpl[module];},_createCollection:function(tab){if(this.context.parent){var module=this.context.parent.get('module');}else{var module=this.module;}
var meta=app.metadata.getModule(module);if(_.isUndefined(meta)){return null;}
var options={};if(meta.fields[tab.link]&&meta.fields[tab.link].type==='link'){options={link:{name:tab.link,bean:this.model}};}
var collection=app.data.createBeanCollection(tab.module,null,options);return collection;},_getCollectionOptions:function(index){var tab=this.tabs[index],options={limit:this.settings.get('limit'),offset:0,params:{order_by:tab.order_by||null,include_child_items:tab.include_child_items||null}};if(tab.module!='Meetings'&&tab.module!='Calls'){options.myItems=this.settings.get('visibility')==='user';}
return options;},_getCollectionFilters:function(index){var tab=this.tabs[index],filters=[];_.each(tab.filters,function(condition,field){var filter={};filter[field]=condition;filters.push(filter);});if((tab.module==='Meetings'||tab.module==='Calls')&&this.settings.get('visibility')==='user'){filters.push({"$or":[{"assigned_user_id":app.user.id},{"users.id":app.user.id}]});}
return filters;},_getFilters:function(index){return[];},loadData:function(options){options=options||{};if(this.disposed||this.meta.config){return;}
var self=this,totalFetches=0;_.each(this.tabs,function(tab,index){tab.collection.options=this._getCollectionOptions(index);tab.collection.filterDef=_.union(this._getCollectionFilters(index),this._getFilters(index));tab.collection.fetch({relate:tab.relate,complete:function(){totalFetches++;tab.collection.dataFetched=true;if(self.disposed||totalFetches<_.size(self.tabs)){return;}
self.collection=self.tabs[self.settings.get('activeTab')].collection;self.render();if(_.isFunction(options.complete)){options.complete.call(this);}}});},this);},showMore:function(){var self=this;this.collection.paginate({limit:this.settings.get('limit'),add:true,success:function(){if(!self.disposed){self.render();}}});},tabSwitcher:function(event){var index=this.$(event.currentTarget).data('index');if(index===this.settings.get('activeTab')){return;}
this.settings.set('activeTab',index);this.collection=this.tabs[index].collection;this.render();},visibilitySwitcher:function(event){var visibility=this.$(event.currentTarget).val();if(visibility===this.settings.get('visibility')){return;}
this.settings.set('visibility',visibility);this.layout.loadData();},_renderHtml:function(){if(this.meta.config){this._super('_renderHtml');return;}
var tab=this.tabs[this.settings.get('activeTab')];_.each(this.collection.models,function(model){model.set('record_date',model.get(tab.record_date));},this);var recordsTpl=this._getRecordsTemplate(tab.module);this.toolbarHtml=this._toolbarTpl(this);this.tabsHtml=this._tabsTpl(this);this.recordsHtml=recordsTpl(this);this._super('_renderHtml');},_dispose:function(){_.each(this.tabs,function(tab){tab.collection.off(null,null,this);});this._super('_dispose');}})