var nv=window.nv||{};nv.version='0.0.1a';nv.dev=false;window.nv=nv;nv.tooltip={};nv.utils={};nv.models={};nv.charts={};nv.graphs=[];nv.logs={};nv.dispatch=d3.dispatch('render_start','render_end');if(nv.dev){nv.dispatch.on('render_start',function(e){nv.logs.startTime=+new Date();});nv.dispatch.on('render_end',function(e){nv.logs.endTime=+new Date();nv.logs.totalTime=nv.logs.endTime-nv.logs.startTime;nv.log('total',nv.logs.totalTime);});}
nv.log=function(){if(nv.dev&&console.log&&console.log.apply)
console.log.apply(console,arguments)
else if(nv.dev&&console.log&&Function.prototype.bind){var log=Function.prototype.bind.call(console.log,console);log.apply(console,arguments);}
return arguments[arguments.length-1];};nv.render=function render(step){step=step||1;nv.render.active=true;nv.dispatch.render_start();setTimeout(function(){var chart,graph;for(var i=0;i<step&&(graph=nv.render.queue[i]);i++){chart=graph.generate();if(typeof graph.callback==typeof(Function))graph.callback(chart);nv.graphs.push(chart);}
nv.render.queue.splice(0,i);if(nv.render.queue.length)setTimeout(arguments.callee,0);else{nv.render.active=false;nv.dispatch.render_end();}},0);};nv.render.active=false;nv.render.queue=[];nv.addGraph=function(obj){if(typeof arguments[0]===typeof(Function))
obj={generate:arguments[0],callback:arguments[1]};nv.render.queue.push(obj);if(!nv.render.active)nv.render();};nv.identity=function(d){return d;};nv.strip=function(s){return s.replace(/(\s|&)/g,'');};function daysInMonth(month,year){return(new Date(year,month+1,0)).getDate();}
function d3_time_range(floor,step,number){return function(t0,t1,dt){var time=floor(t0),times=[];if(time<t0)step(time);if(dt>1){while(time<t1){var date=new Date(+time);if((number(date)%dt===0))times.push(date);step(time);}}else{while(time<t1){times.push(new Date(+time));step(time);}}
return times;};}
d3.time.monthEnd=function(date){return new Date(date.getFullYear(),date.getMonth(),0);};d3.time.monthEnds=d3_time_range(d3.time.monthEnd,function(date){date.setUTCDate(date.getUTCDate()+1);date.setDate(daysInMonth(date.getMonth()+1,date.getFullYear()));},function(date){return date.getMonth();});function d3_scale_quantile(domain,range){var thresholds;function rescale(){var k=0,q=range.length;thresholds=[];while(++k<q)thresholds[k-1]=d3.quantile(domain,k / q);return scale;}
function scale(x){if(isNaN(x=+x))return NaN;return range[d3.bisect(thresholds,x)];}
scale.domain=function(x){if(!arguments.length)return domain;domain=x.filter(function(d){return!isNaN(d);}).sort(d3.ascending);return rescale();};scale.range=function(x){if(!arguments.length)return range;range=x;return rescale();};scale.ticks=function(m){return d3_scale_linearTicks(scale.domain(),m);};scale.quantiles=function(){return thresholds;};scale.copy=function(){return d3_scale_quantile(domain,range);};return rescale();}
d3.scale.quantile=function(){return d3_scale_quantile([],[]);};