
(function(){var nvtooltip=window.nv.tooltip={};nvtooltip.show=function(pos,content,gravity,dist,parentContainer,classes){var container=document.createElement('div'),inner=document.createElement('div'),arrow=document.createElement('div'),body=document.getElementsByTagName('body')[0];gravity=gravity||'s';dist=dist||10;inner.className='tooltip-inner';arrow.className='tooltip-arrow';inner.innerHTML=content;container.style.left=0;container.style.top=-1000;container.style.opacity=0;container.className='tooltip xy-tooltip in';container.appendChild(inner);container.appendChild(arrow);body.appendChild(container);nvtooltip.position(container,pos,gravity,dist);container.style.opacity=1;return container;};nvtooltip.cleanup=function(){var tooltips=document.getElementsByClassName('tooltip');var purging=[];while(tooltips.length){purging.push(tooltips[0]);tooltips[0].style.transitionDelay='0 !important';tooltips[0].style.opacity=0;tooltips[0].className='nvtooltip-pending-removal out';}
setTimeout(function(){while(purging.length){var removeMe=purging.pop();removeMe.parentNode.removeChild(removeMe);}},500);};nvtooltip.position=function(container,pos,gravity,dist){var body=document.getElementsByTagName('body')[0];gravity=gravity||'s';dist=dist||10;var height=parseInt(container.offsetHeight,10),width=parseInt(container.offsetWidth,10),windowWidth=nv.utils.windowSize().width,windowHeight=nv.utils.windowSize().height,scrollTop=body.scrollTop,scrollLeft=body.scrollLeft,class_name=container.className.replace(/ top| right| bottom| left/g,''),left,top;function alignCenter(){var left=pos[0]-(width / 2);if(left<scrollLeft)left=scrollLeft+5;if(left+width>windowWidth)left=windowWidth-width-5;return left;}
function alignMiddle(){var top=pos[1]-(height / 2);if(top<scrollTop)top=scrollTop+5;if(top+height>scrollTop+windowHeight)top=scrollTop-height-5;return top;}
switch(gravity){case'e':top=alignMiddle();left=pos[0]-width-dist;if(left<scrollLeft){left=pos[0]+dist;class_name+=' right';}else{class_name+=' left';}
break;case'w':top=alignMiddle();left=pos[0]+dist;if(left+width>windowWidth){left=pos[0]-width-dist;class_name+=' left';}else{class_name+=' right';}
break;case'n':left=alignCenter();top=pos[1]+dist;if(top+height>scrollTop+windowHeight){top=pos[1]-height-dist;class_name+=' top';}else{class_name+=' bottom';}
break;case's':left=alignCenter();top=pos[1]-height-dist;if(scrollTop>top){top=pos[1]+10;class_name+=' bottom';}else{class_name+=' top';}
break;}
container.style.left=left+'px';container.style.top=top+'px';container.className=class_name;};})();