<?php

/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Audit/language/tr_TR.lang.php, V_6.5.2 Mon 17/09/12 18:59:58 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s): 
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_FIELD_NAME' => 'Alan' ,
   'LBL_OLD_NAME' => 'Eski Değer' ,
   'LBL_NEW_VALUE' => 'Yeni Değer' ,
   'LBL_CREATED_BY' => 'Değiştiren' ,
   'LBL_LIST_DATE' => 'Değiştirilme Tarihi:' ,
   'LBL_AUDITED_FIELDS' => 'Bu modülde denetlenmiş alanlar:' ,
   'LBL_NO_AUDITED_FIELDS_TEXT' => 'Bu modülde değişiklik tarihçesi alanı bulunmamaktadır' ,
   'LBL_CHANGE_LOG' => 'Değişiklik Tarihçesi' );

?>
