/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
(function(app){app.events.on("app:init",function(){var tagTemplate=Handlebars.compile('<span class="label label-{{module}} sugar_tag"><a href="#{{buildRoute module=module id=id}}">{{name}}</a></span>'),tagInEditTemplate=Handlebars.compile('<span class="label label-{{module}} sugar_tag" contenteditable="false"><a>{{name}}</a></span>'),tagListOptionTemplate=Handlebars.compile('<li{{#if noAccess}} class="disabled"{{/if}}><a><div class="label label-module-mini label-{{module}} pull-left">{{moduleIconLabel module}}</div>{{{htmlName}}}{{#if noAccess}}<div class="add-on">{{str "LBL_NO_ACCESS_LOWER"}}</div>{{/if}}</a></li>'),tagTextTemplate=Handlebars.compile('@[{{module}}:{{id}}:{{name}}]'),taggingHtml='<span class="sugar_tagging">&nbsp;</span>',tagListContainerHtml='<ul class="dropdown-menu activitystream-tag-dropdown"></ul>',mention='@',reference='#',keycode_at=64,keycode_hash=35,keycode_esc=27,keycode_enter=13,keycode_tab=9,keycode_up=38,keycode_down=40,tagRegExp=/@\[([\w]+):([\d\w\-]+):(.+?)\]/g,nbspRegExp=/&nbsp;/g;app.plugins.register('Taggable',['view'],{events:{'keypress .taggable':'_checkForReferenceOrMention','keydown .taggable':'_onKeydown','keyup .taggable':'_onKeyup','mouseover .activitystream-tag-dropdown li':'_setListOptionAsActive','click .activitystream-tag-dropdown li':'_insertTag'},taggableSearchAfter:2,taggableListLength:8,onAttach:function(component,plugin){this._searchForTags=_.debounce(this._searchForTags,300);$(document).on('click.'+component.cid,function(event){var $target=$(event.target),clickedOutsideDropdown=($target.parents('.activitystream-tag-dropdown').length===0),clickedOutsideTaggingSpan=!$target.hasClass('sugar_tagging');if(component._taggableEnabled&&clickedOutsideDropdown&&clickedOutsideTaggingSpan){component._resetTaggable();}});},onDetach:function(component,plugin){$(document).off('click.'+component.cid);},unformatTags:function($input){var text='',tags=[];$input.contents().each(function(){var $node=$(this),data=$node.data();if(this.nodeType===Node.TEXT_NODE){text+=this.nodeValue.replace(nbspRegExp,' ');}else if(data&&data.module&&data.id&&data.name){text+=tagTextTemplate(data);tags.push(data);}else{text+=$node.text();}});return{value:$.trim(text),tags:this._filterOutDuplicateTags(tags)};},formatTags:function(text){var html='';if(text&&(text.length>0)){html=text.replace(tagRegExp,function(str,module,id,name){name=new Handlebars.SafeString(name);return tagTemplate({module:module,id:id,name:name});});}
return $.trim(html);},setTaggableRecord:function(module,id){this._taggableModuleName=module;this._taggableModelId=id;},_taggableEnabled:false,_taggableModuleName:null,_taggableModelId:null,_taggableLastSearchTerm:null,_taggableListOpen:null,_checkForReferenceOrMention:function(event){if(!this._taggableEnabled){switch(event.which){case keycode_at:case keycode_hash:this._enableTaggable();break;}}},_onKeydown:function(event){if(this._taggableEnabled&&!this._taggableListOpen){switch(event.which){case keycode_esc:case keycode_enter:case keycode_tab:event.preventDefault();this._resetTaggable();break;}}
if(this._taggableEnabled&&(this._taggableListOpen===true)){switch(event.which){case keycode_esc:event.preventDefault();this._resetTaggable();break;case keycode_enter:case keycode_tab:event.preventDefault();this._getCurrentlyActiveOption().click();break;case keycode_up:event.preventDefault();this._selectNextListOption(false);break;case keycode_down:event.preventDefault();this._selectNextListOption(true);break;}}},_onKeyup:function(event){var selection=window.getSelection(),range,$container,searchTerm;if(this._taggableEnabled){if(this._taggableListOpen&&(event.which===keycode_enter||event.which===keycode_tab||event.which==keycode_up||event.which==keycode_down)){return;}
if(selection.rangeCount>0){range=selection.getRangeAt(0);$container=$(range.startContainer.parentNode);searchTerm=$.trim($container.text());if(!$container.hasClass('sugar_tagging')){this._resetTaggable();}else if(this._taggableListOpen&&(searchTerm.length<=this.taggableSearchAfter)){this._getDropdown().hide();this._taggableListOpen=null;this._taggableLastSearchTerm=null;}else{if((searchTerm.indexOf(mention)===0)||(searchTerm.indexOf(reference)===0)){this._searchForTags(searchTerm);}else{this._resetTaggable();}}}}},_enableTaggable:function(){var selection=window.getSelection(),range=selection.getRangeAt(0),tagElement=$(taggingHtml),textNode=tagElement.contents()[0],cursorPosition=$.browser.webkit?1:0;if(this._shouldEnableTaggable(range)){range.insertNode(tagElement.get(0));range.setStart(textNode,cursorPosition);range.setEnd(textNode,cursorPosition);selection.removeAllRanges();selection.addRange(range);this._taggableEnabled=true;}},_shouldEnableTaggable:function(range){var text=range.startContainer.nodeValue,charBeforeCursor,result=false;if((range.startContainer.nodeType===Node.ELEMENT_NODE)||(text.length===0)||(range.startOffset===0)){result=true;}else{charBeforeCursor=text.charAt(range.startOffset-1);if((charBeforeCursor===String.fromCharCode(160))||(charBeforeCursor===String.fromCharCode(32))){result=true;}}
return result;},_resetTaggable:function(){var $taggable=this._getTaggableInput().focus(),selection=window.getSelection(),range=selection.getRangeAt(0),$taggingSpan;if(this._taggableEnabled){$taggingSpan=$taggable.find('.sugar_tagging');if($taggingSpan.length>0){range.selectNodeContents($taggingSpan.get(0));range.collapse(false);selection.removeAllRanges();selection.addRange(range);$taggingSpan.before($.trim($taggingSpan.text())).remove();}else{$taggable.blur().focus();}
this._removeDropdown();this._taggableEnabled=false;this._taggableListOpen=null;this._taggableLastSearchTerm=null;}},_insertTag:function(event){var $selected=$(event.currentTarget),$taggable=this._getTaggableInput(),taggableData=$selected.data(),$tagToReplace=$taggable.find('.sugar_tagging'),selection,range,$tagHtml;if(!$selected.hasClass('disabled')){$taggable.focus();selection=window.getSelection();range=selection.getRangeAt(0);$tagHtml=$(tagInEditTemplate(taggableData));range.selectNode($tagToReplace.get(0));range.insertNode($tagHtml.get(0));range.selectNode($tagHtml.get(0));range.collapse(false);selection.removeAllRanges();selection.addRange(range);$tagToReplace.before('&nbsp;').remove();$tagHtml.data({id:taggableData.id,name:taggableData.name,module:taggableData.module});this._removeDropdown();this._taggableEnabled=false;this._taggableListOpen=null;this._taggableLastSearchTerm=null;}
event.preventDefault();},_searchForTags:function(searchTerm){var searchParams,referenceSearchFields=['name','first_name','last_name'],tagAction=searchTerm.charAt(0);searchTerm=$.trim(searchTerm.substr(1));if((searchTerm.length>=this.taggableSearchAfter)&&(searchTerm!==this._taggableLastSearchTerm)){searchParams={q:searchTerm,max_num:this.taggableListLength,fields:'name'};if((this._taggableListOpen===false)&&(searchTerm.indexOf(this._taggableLastSearchTerm)===0)){this._resetTaggable();}else{if(tagAction===mention){app.data.createBeanCollection("Users").fetch({success:_.bind(function(collection,resp){if(this._taggableEnabled&&resp){this._populateTagList(collection,searchTerm);}},this),filter:this.getFilterDef("Users",searchTerm),params:{has_access_module:this._taggableModuleName,has_access_record:this._taggableModelId}});}else if(tagAction===reference){searchParams.search_fields=referenceSearchFields.join();app.api.search(searchParams,{success:_.bind(function(response){if(this._taggableEnabled&&response){this._populateTagList(app.data.createMixedBeanCollection(response.records),searchTerm);}},this)});}
this._taggableLastSearchTerm=searchTerm;}}},_populateTagList:function(collection,searchTerm){var $tagList=this._initializeDropdown(),currentSearchTerm;if(collection.length>0){searchTerm=$.trim(searchTerm);currentSearchTerm=$.trim(this._getTaggableInput().find('.sugar_tagging').text());if($.trim(currentSearchTerm.substr(1))!==searchTerm){this._taggableLastSearchTerm=null;return;}
collection.each(function(model,index){var htmlName=model.get('name').replace(new RegExp('('+searchTerm+')','ig'),function($1,match){return'<strong>'+match+'</strong>';}),data={module:model.get('_module'),id:model.get('id'),name:model.get('name'),htmlName:htmlName,noAccess:(model.get('has_access')===false)},$tagListOption=$(tagListOptionTemplate(data)).data(data);$tagList.append($tagListOption);},this);this._selectNextListOption(true);this._taggableListOpen=true;$tagList.show();}else{this._taggableListOpen=false;$tagList.hide();}},_initializeDropdown:function(){var $dropdown=this._getDropdown(),$taggable=this._getTaggableInput();if($dropdown.length===0){$dropdown=$(tagListContainerHtml).hide().appendTo($taggable.parent()).css('top',$taggable.outerHeight());}else{$dropdown.empty();}
return $dropdown;},_getDropdown:function(){return this.$('.activitystream-tag-dropdown');},_removeDropdown:function(){this.$('.activitystream-tag-dropdown').remove();},_getCurrentlyActiveOption:function(){return this._getDropdown().find('.active');},_selectNextListOption:function(down,$current){var $next;$current=$current||this._getCurrentlyActiveOption();if($current.length===0){$next=this._getDropdown().children().first();}else{$next=down?$current.next():$current.prev();}
if($next.length>0){$current.removeClass('active');if($next.hasClass('disabled')){this._selectNextListOption(down,$next);}else{$next.addClass('active');}}},_setListOptionAsActive:function(event){var currentTarget=this.$(event.currentTarget);if(!currentTarget.hasClass('disabled')){this._getDropdown().find('.active').removeClass('active');currentTarget.addClass('active');}},_getTaggableInput:function(){return this.$('.taggable');},_filterOutDuplicateTags:function(tags){tags=_.uniq(tags,function(tag){return tag.id;});return tags;}});});})(SUGAR.App);