/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
function loadSugarChart(chartId,jsonFilename,css,chartConfig,params,callback){this.chartObject="";if(document.getElementById(chartId)==null){return false;}
var labelType='Native',useGradients=false,animate=false,that=this,contentEl='content',minColumnWidth=40;params=params?params:{};contentEl=params.contentEl||contentEl;minColumnWidth=params.minColumnWidth||minColumnWidth;switch(chartConfig["chartType"]){case"d3-barChart":SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){var json=data;var marginBottom=(chartConfig["orientation"]=='vertical'&&data.values.length>8)?20*4:20;var paretoChart=nv.models.paretoChart().margin({top:0,right:10,bottom:20,left:30}).showTitle(false).tooltips(true).tooltipLine(function(key,x,y,e,graph){var val=App.currency.formatAmountLocale(e.point.y)
return'<p>'+key+': <b>'+val+'</b></p>'}).tooltipBar(function(key,x,y,e,graph){var val=App.currency.formatAmountLocale(e.value)
return'<p>'+SUGAR.App.lang.get('LBL_SALES_STAGE','Forecasts')+': <b>'+key+'</b></p>'+'<p>'+SUGAR.App.lang.get('LBL_AMOUNT','Forecasts')+': <b>'+val+'</b></p>'+'<p>'+SUGAR.App.lang.get('LBL_PERCENT','Forecasts')+': <b>'+x+'%</b></p>'}).showControls(false).colorData('default').colorFill('default').stacked(!params.display_manager).id(chartId);var chartId=params.chartId||'db620e51-8350-c596-06d1-4f866bfcfd5b';d3.select('#'+chartId+' svg').remove();d3.select('#'+chartId).append('svg').datum(SUGAR.charts.translateDataToD3(json,params)).transition().duration(500).call(paretoChart).selectAll('.nv-y.nv-axis .tick').select('text').text(function(d){return App.user.get('preferences').currency_symbol+d3.format(',.2s')(d);});nv.utils.windowResize(paretoChart.update);that.chartObject=paretoChart;SUGAR.charts.setChartObject(paretoChart);}
SUGAR.charts.callback(callback);});break;case"barChart":SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){var json=data;var properties=$jit.util.splat(data.properties)[0];var marginBottom=(chartConfig["orientation"]=='vertical'&&data.values.length>8)?20*4:20;if(chartConfig["orientation"]=='vertical')
{function fixChartContainer(event,itemsCount)
{var chartCanvas=$("div.chartCanvas");var chartContainer=$("div.chartContainer");var region=$('#'+contentEl);if(chartContainer.length>0&&chartCanvas.length>0)
{if(region&&region.width)
{var realWidth=itemsCount*parseInt(minColumnWidth,10);chartContainer=chartContainer.first();chartCanvas=chartCanvas.first();if(realWidth>region.width)
{chartContainer.width(region.width()+'px');chartCanvas.width(realWidth+'px');}
else
{chartContainer.width(region.width()+'px');chartCanvas.width(region.width()+'px');}}}
if(!event)
{$(window).resize(function(length){return function(event){fixChartContainer(event,length);}}(json.values.length));}}
fixChartContainer(null,json.values.length);}
var barChart=new $jit.BarChart({injectInto:chartId,animate:animate,nodeCount:data.values.length,renderBackground:chartConfig['imageExportType']=="jpg"?true:false,dataPointSize:chartConfig["dataPointSize"],backgroundColor:'rgb(255,255,255)',colorStop1:'rgba(255,255,255,.8)',colorStop2:'rgba(255,255,255,0)',shadow:{enable:false,size:2},orientation:chartConfig["orientation"],hoveredColor:false,Title:{text:properties['title'],size:16,color:'#444444',offset:20},Subtitle:{text:properties['subtitle'],size:11,color:css["color"],offset:20},Ticks:{enable:true,color:css["gridLineColor"]},barsOffset:(chartConfig["orientation"]=="vertical")?20:20,Margin:{top:20,left:30,right:20,bottom:marginBottom},ScrollNote:{text:(chartConfig["scroll"]&&$jit.util.isTouchScreen())?"Use two fingers to scroll":"",size:12},Events:{enable:true,onClick:function(node){if(!node||$jit.util.isTouchScreen())return;if(node.link==undefined||node.link=='')return;window.location.href=node.link;}},labelOffset:5,type:useGradients?chartConfig["barType"]+':gradient':chartConfig["barType"],showAggregates:(chartConfig["showAggregates"]!=undefined)?chartConfig["showAggregates"]:true,showNodeLabels:(chartConfig["showNodeLabels"]!=undefined)?chartConfig["showNodeLabels"]:true,segmentStacked:(chartConfig["segmentStacked"]!=undefined)?chartConfig["segmentStacked"]:false,showLabels:true,Label:{type:labelType,size:12,family:css["font-family"],color:css["color"],colorAlt:"#ffffff"},Tips:{enable:true,onShow:function(tip,elem){if(elem.type=='marker'){tip.innerHTML='<b>'+elem.name+'</b>: '+elem.valuelabel;}else{if(elem.link!=undefined&&elem.link!=''){drillDown=($jit.util.isTouchScreen())?"<br><a href='"+elem.link+"'>Click to drilldown</a>":"<br>Click to drilldown";}else{drillDown="";}
if(elem.valuelabel!='undefined'&&elem.valuelabel!=undefined&&elem.valuelabel!=''){value="elem.valuelabel";}else{value="elem.value";}
if(properties.label_name!=undefined&&properties.label_name!=""){eval("tip.innerHTML = properties.label_name + ': <b>' + elem."+chartConfig["tip"]+" + '</b><br> '+properties.value_name+': <b>' + "+value+" + '</b>' + drillDown");}else{eval("tip.innerHTML = '<b>' + elem."+chartConfig["tip"]+" + '</b>: ' + "+value+" + ' - ' + elem.percentage + '%' + drillDown");}}}}});barChart.loadJSON(data);var list=SUGAR.charts.generateLegend(barChart,chartId);$jit.util.saveImageTest(chartId,jsonFilename,chartConfig["imageExportType"],chartConfig['saveImageTo']);SUGAR.charts.trackWindowResize(barChart,chartId,data);barChart.json=json;that.chartObject=barChart;SUGAR.charts.setChartObject(barChart);}
SUGAR.charts.callback(callback);});break;case"lineChart":SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){var properties=$jit.util.splat(data.properties)[0];var lineChart=new $jit.LineChart({injectInto:chartId,animate:animate,renderBackground:chartConfig['imageExportType']=="jpg"?true:false,backgroundColor:'rgb(255,255,255)',colorStop1:'rgba(255,255,255,.8)',colorStop2:'rgba(255,255,255,0)',selectOnHover:false,Title:{text:properties['title'],size:16,color:'#444444',offset:20},Subtitle:{text:properties['subtitle'],size:11,color:css["color"],offset:20},Ticks:{enable:true,color:css["gridLineColor"]},Margin:{top:20,left:40,right:40,bottom:20},Events:{enable:true,onClick:function(node){if(!node||$jit.util.isTouchScreen())return;if(node.link==undefined||node.link=='')return;window.location.href=node.link;}},labelOffset:5,type:useGradients?chartConfig["lineType"]+':gradient':chartConfig["lineType"],showAggregates:true,showLabels:true,Label:{type:labelType,size:12,family:css["font-family"],color:css["color"],colorAlt:"#ffffff"},Tips:{enable:true,onShow:function(tip,elem){if(elem.link!=undefined&&elem.link!=''){drillDown=($jit.util.isTouchScreen())?"<br><a href='"+elem.link+"'>Click to drilldown</a>":"<br>Click to drilldown";}else{drillDown="";}
if(elem.valuelabel!='undefined'&&elem.valuelabel!=undefined&&elem.valuelabel!=''){var value="elem.valuelabel";}else{var value="elem.value";}
if(elem.collision){eval("var name = elem."+chartConfig["tip"]+";");var content='<table>';for(var i=0;i<name.length;i++){content+='<tr><td><b>'+name[i]+'</b>:</td><td> '+elem.value[i]+' - '+elem.percentage[i]+'%'+'</td></tr>';}
content+='</table>';tip.innerHTML=content;}else{eval("tip.innerHTML = '<b>' + elem."+chartConfig["tip"]+" + '</b>: ' + "+value+" + ' - ' + elem.percentage + '%' + drillDown");}}}});lineChart.loadJSON(data);var list=SUGAR.charts.generateLegend(lineChart,chartId);$jit.util.saveImageTest(chartId,jsonFilename,chartConfig["imageExportType"]);SUGAR.charts.trackWindowResize(lineChart,chartId,data);that.chartObject=lineChart;}
SUGAR.charts.callback(callback);});break;case"pieChart":SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){var properties=$jit.util.splat(data.properties)[0];var pieChart=new $jit.PieChart({injectInto:chartId,animate:animate,renderBackground:chartConfig['imageExportType']=="jpg"?true:false,backgroundColor:'rgb(255,255,255)',colorStop1:'rgba(255,255,255,.8)',colorStop2:'rgba(255,255,255,0)',labelType:properties['labels'],hoveredColor:false,offset:50,sliceOffset:0,labelOffset:30,type:useGradients?chartConfig["pieType"]+':gradient':chartConfig["pieType"],showLabels:true,Title:{text:properties['title'],size:16,color:'#444444',offset:20},Subtitle:{text:properties['subtitle'],size:11,color:css["color"],offset:20},Margin:{top:20,left:20,right:20,bottom:20},Events:{enable:true,onClick:function(node){if(!node||$jit.util.isTouchScreen())return;if(node.link==undefined||node.link=='')return;window.location.href=node.link;}},Label:{type:labelType,size:12,family:css["font-family"],color:css["color"]},Tips:{enable:true,onShow:function(tip,elem){if(elem.link!=undefined&&elem.link!=''){drillDown=($jit.util.isTouchScreen())?"<br><a href='"+elem.link+"'>Click to drilldown</a>":"<br>Click to drilldown";}else{drillDown="";}
if(elem.valuelabel!='undefined'&&elem.valuelabel!=undefined&&elem.valuelabel!=''){value="elem.valuelabel";}else{value="elem.value";}
eval("tip.innerHTML = '<b>' + elem.label + '</b>: ' + "+value+" + ' - ' + elem.percentage + '%' + drillDown");}}});pieChart.loadJSON(data);var list=SUGAR.charts.generateLegend(pieChart,chartId);$jit.util.saveImageTest(chartId,jsonFilename,chartConfig["imageExportType"]);SUGAR.charts.trackWindowResize(pieChart,chartId,data);that.chartObject=pieChart;}
SUGAR.charts.callback(callback);});break;case"funnelChart":SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){var properties=$jit.util.splat(data.properties)[0];var funnelChart=new $jit.FunnelChart({injectInto:chartId,animate:animate,renderBackground:chartConfig['imageExportType']=="jpg"?true:false,backgroundColor:'rgb(255,255,255)',colorStop1:'rgba(255,255,255,.8)',colorStop2:'rgba(255,255,255,0)',orientation:"vertical",hoveredColor:false,Title:{text:properties['title'],size:16,color:'#444444',offset:20},Subtitle:{text:properties['subtitle'],size:11,color:css["color"],offset:20},segmentOffset:20,Margin:{top:20,left:20,right:20,bottom:20},Events:{enable:true,onClick:function(node){if(!node||$jit.util.isTouchScreen())return;if(node.link==undefined||node.link=='')return;window.location.href=node.link;}},labelOffset:10,type:useGradients?chartConfig["funnelType"]+':gradient':chartConfig["funnelType"],showAggregates:true,showLabels:true,Label:{type:labelType,size:12,family:css["font-family"],color:css["color"],colorAlt:"#ffffff"},Tips:{enable:true,onShow:function(tip,elem){if(elem.link!=undefined&&elem.link!=''){drillDown=($jit.util.isTouchScreen())?"<br><a href='"+elem.link+"'>Click to drilldown</a>":"<br>Click to drilldown";}else{drillDown="";}
if(elem.valuelabel!='undefined'&&elem.valuelabel!=undefined&&elem.valuelabel!=''){value="elem.valuelabel";}else{value="elem.value";}
eval("tip.innerHTML = '<b>' + elem."+chartConfig["tip"]+" + '</b>: ' + "+value+"  + ' - ' + elem.percentage + '%' +  drillDown");}}});funnelChart.loadJSON(data);var list=SUGAR.charts.generateLegend(funnelChart,chartId);$jit.util.saveImageTest(chartId,jsonFilename,chartConfig["imageExportType"]);SUGAR.charts.trackWindowResize(funnelChart,chartId,data);that.chartObject=funnelChart;}
SUGAR.charts.callback(callback);});break;case"gaugeChart":SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){var properties=$jit.util.splat(data.properties)[0];var gaugeChart=new $jit.GaugeChart({injectInto:chartId,animate:animate,renderBackground:chartConfig['imageExportType']=="jpg"?true:false,backgroundColor:'rgb(255,255,255)',colorStop1:'rgba(255,255,255,.8)',colorStop2:'rgba(255,255,255,0)',labelType:properties['labels'],hoveredColor:false,Title:{text:properties['title'],size:16,color:'#444444',offset:20},Subtitle:{text:properties['subtitle'],size:11,color:css["color"],offset:5},offset:20,gaugeStyle:{backgroundColor:'#aaaaaa',borderColor:'#999999',needleColor:'rgba(255,0,0,.8)',borderSize:4,positionFontSize:24,positionOffset:2},type:useGradients?chartConfig["gaugeType"]+':gradient':chartConfig["gaugeType"],showLabels:true,Events:{enable:true,onClick:function(node){if(!node||$jit.util.isTouchScreen())return;if(node.link==undefined||node.link=='')return;window.location.href=node.link;}},Label:{type:labelType,size:12,family:css["font-family"],color:css["color"]},Tips:{enable:true,onShow:function(tip,elem){if(elem.link!=undefined&&elem.link!=''){drillDown=($jit.util.isTouchScreen())?"<br><a href='"+elem.link+"'>Click to drilldown</a>":"<br>Click to drilldown";}else{drillDown="";}
if(elem.valuelabel!='undefined'&&elem.valuelabel!=undefined&&elem.valuelabel!=''){value="elem.valuelabel";}else{value="elem.value";}
eval("tip.innerHTML = '<b>' + elem.label + '</b>: ' + "+value+" + drillDown");}}});gaugeChart.loadJSON(data);var list=SUGAR.charts.generateLegend(gaugeChart,chartId);$jit.util.saveImageTest(chartId,jsonFilename,chartConfig["imageExportType"]);SUGAR.charts.trackWindowResize(gaugeChart,chartId,data);that.chartObject=gaugeChart;}
SUGAR.charts.callback(callback);});break;}}
function updateChart(jsonFilename,chart,params){params=params?params:{};SUGAR.charts.get(jsonFilename,params,function(data){if(SUGAR.charts.isDataEmpty(data)){chart.busy=false;chart.updateJSON(data);}});}
function swapChart(chartId,jsonFilename,css,chartConfig){$("#"+chartId).empty();$("#legend"+chartId).empty();$("#tiptip_holder").empty();var chart=new loadSugarChart(chartId,jsonFilename,css,chartConfig);return chart;}
(function($){if(typeof SUGAR=="undefined"||!SUGAR){SUGAR={};}
SUGAR.charts={chart:null,callback:function(callback){if(callback){callback(this.chart);}},setChartObject:function(chart){this.chart=chart;},generateLegend:function(chart,chartId){var list=$jit.id('legend'+chartId);var legend=chart.getLegend();if(typeof legend['wmlegend']!="undefined"&&legend['wmlegend']['name'].length>0){var table="<div class='col'>";}else{var table="<div class='row'>";}
for(var i=0;i<legend['name'].length;i++){if(legend["name"][i]!=undefined){table+="<div class='legendGroup'>";table+='<div class=\'query-color\' style=\'background-color:'
+legend["color"][i]+'\'></div>';table+='<div class=\'label\'>';table+=legend["name"][i];table+='</div>';table+="</div>";}}
table+="</div>";if(typeof legend['wmlegend']!="undefined"&&legend['wmlegend']['name'].length>0){table+="<div class='col2'>";for(var i=0;i<legend['wmlegend']['name'].length;i++){table+="<div class='legendGroup'>";table+="<div class='waterMark  "+legend["wmlegend"]['type'][i]+"' style='background-color: "+legend["wmlegend"]['color'][i]+";'></div>";table+="<div class='label'>"+legend["wmlegend"]['name'][i]+"</div>";table+="</div>";}
table+="</div>";}
list.innerHTML=table;jQuery('#legend'+chartId).ready(function(){var chartWidth=jQuery('#'+chartId).width();chartWidth=chartWidth-20;$('#legend'+chartId).width(chartWidth);var legendGroupWidth=new Array();if(typeof legend['wmlegend']!="undefined"&&legend['wmlegend']['name'].length>0){var sel=".col .legendGroup";}else{var sel=".row .legendGroup";}
$(sel).each(function(index){legendGroupWidth[index]=$(this).width();});var largest=Math.max.apply(Math,legendGroupWidth);$(sel).width(largest+2);});return list;},get:function(url,params,success){var data={r:new Date().getTime()};$.extend(data,params);$.ajax({url:url,data:data,dataType:'json',async:false,success:success});},isDataEmpty:function(data){if(data!==undefined&&data!=="No Data"&&data!==""){return true;}else{return false;}},trackWindowResize:function(chart,chartId,json){var timeout,delay=500,origWindowWidth=document.documentElement.scrollWidth,container=document.getElementById(chartId),widget=document.getElementById(chartId+"-canvaswidget");$(window).resize(function(){if(timeout){clearTimeout(timeout);}
timeout=setTimeout(function(){var newWindowWidth=document.documentElement.scrollWidth;if(newWindowWidth!=origWindowWidth){widget.style.display="none";setTimeout(function(){var width=container.offsetWidth;var chartWidth=width-20;$('#legend'+chartId).width(chartWidth);widget.style.display="";chart.resizeGraph(json,width);origWindowWidth=newWindowWidth;},0);}},delay);});},update:function(chart,url,params,callback){var self=this;params=params?params:{};self.chart=chart;this.get(url,params,function(data){if(self.isDataEmpty(data)){self.chart.busy=false;self.chart.updateJSON(data);self.callback(callback);}});}}})(jQuery);