/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({backdropHtml:"<div class='drawer-backdrop'></div>",plugins:['Tooltip'],onCloseCallback:null,scrollTopPositions:[],pixelsFromFooter:60,initialize:function(options){if(!this.$el.is('#drawers')){app.logger.error('Drawer layout can only be included as an Additional Component.');return;}
app.drawer=this;this.onCloseCallback=[];this.name='drawer';app.routing.before("route",this.reset,this,true);app.view.Layout.prototype.initialize.call(this,options);},open:function(layoutDef,onClose){var layout;if(_.isUndefined(onClose)){this.onCloseCallback.push(function(){});}else{this.onCloseCallback.push(onClose);}
if(_.isUndefined(layoutDef.context)){layoutDef.context={};}
if(_.isUndefined(layoutDef.context.forceNew)){layoutDef.context.forceNew=true;}
this._addComponentsFromDef([layoutDef]);layout=_.last(this._components);this._scrollToTop();this._animateOpenDrawer(_.bind(function(){app.trigger("app:view:change",layout.options.name,layout.context.attributes);},this));layout.loadData();layout.render();},close:function(){var self=this,args=Array.prototype.slice.call(arguments,0);if(!Modernizr.csstransitions){this.closeImmediately.apply(this,args);return;}
if(this._components.length>0){this._animateCloseDrawer(function(){var layout;self._components.pop().dispose();layout=_.last(self._components);self._scrollBackToOriginal(layout);if(layout){app.trigger("app:view:change",layout.options.name,layout.context.attributes);}else{app.trigger("app:view:change",app.controller.context.get("layout"),app.controller.context.attributes);}
(self.onCloseCallback.pop()).apply(this,args);});}},closeImmediately:function(){if(this._components.length>0){var args=Array.prototype.slice.call(arguments,0),drawers=this._getDrawers(false),drawerHeight=this._determineDrawerHeight();drawers.$top.removeClass('transition').removeClass('active');drawers.$bottom.removeClass('transition').removeClass('inactive').addClass('active');if(drawers.$next){drawers.$next.removeClass('transition');}
drawers.$bottom.css('top','');if(drawers.$next){drawers.$next.css('top',this._isMainAppContent(drawers.$next)?drawerHeight:drawers.$next.offset().top-drawerHeight);}
this._cleanUpAfterClose(drawers);drawers.$bottom.addClass('transition');if(drawers.$next){drawers.$next.addClass('transition');}
this._components.pop().dispose();this._scrollBackToOriginal(_.last(this._components));(this.onCloseCallback.pop()).apply(window,args);}},load:function(layoutDef){var layout=this._components.pop(),top=layout.$el.css('top'),height=layout.$el.css('height'),drawers;layout.dispose();this._addComponentsFromDef([layoutDef]);drawers=this._getDrawers(true);drawers.$next.addClass('drawer').css({top:top,height:height});this._removeTabAndBackdrop(drawers.$top);this._createTabAndBackdrop(drawers.$next,drawers.$top);layout=_.last(this._components);layout.loadData();layout.render();},count:function(){return this._components.length;},isActive:function(el){return((this.count()===0)||($(el).parents('.drawer.active').length>0));},reset:function(triggerBefore){triggerBefore=triggerBefore===false?false:true;if(triggerBefore&&!this.triggerBefore("reset",{drawer:this})){return false;}
var $main=app.$contentEl.children().first();_.each(this._components,function(component){component.dispose();},this);this._components=[];this.onCloseCallback=[];if($main.hasClass('drawer')){$main.removeClass('drawer').css('top','');this._removeTabAndBackdrop($main);}
$('body').removeClass('noscroll');app.$contentEl.removeClass('noscroll');},_animateOpenDrawer:function(callback){if(this._components.length===0){return;}
var drawers=this._getDrawers(true),drawerHeight=this._determineDrawerHeight();if(this._isMainAppContent(drawers.$top)){drawers.$top.addClass('drawer');$('body').addClass('noscroll');app.$contentEl.addClass('noscroll');}
this._createTabAndBackdrop(drawers.$next,drawers.$top);drawers.$next.addClass('drawer');drawers.$next.css('height',drawerHeight);drawers.$next.css('top',drawers.$top.offset().top-drawerHeight);_.defer(_.bind(function(){if(drawers.$bottom){drawers.$bottom.addClass('transition').css('top',drawers.$bottom.offset().top+drawerHeight);}
drawers.$top.addClass('transition inactive').removeClass('active').css('top',this._isMainAppContent(drawers.$top)?drawerHeight:drawers.$top.offset().top+drawerHeight);drawers.$next.addClass('transition active').css('top','');if(this._components.length===1){$(window).on('resize.drawer',_.bind(this._resizeDrawer,this));}
if(_.isFunction(callback)){callback();}},this));this.trigger('drawer:resize',drawerHeight);},_animateCloseDrawer:function(callback){if(this._components.length===0){return;}
var drawers=this._getDrawers(false),drawerHeight=this._determineDrawerHeight(),transitionEndEvents='webkitTransitionEnd oTransitionEnd otransitionend transitionend msTransitionEnd';drawers.$bottom.one(transitionEndEvents,_.bind(function(){drawers.$bottom.off(transitionEndEvents);this._cleanUpAfterClose(drawers);callback();},this));drawers.$top.removeClass('active').css('top',drawers.$top.offset().top-drawerHeight);drawers.$bottom.removeClass('inactive').addClass('active').css('top','');_.delay(function(){drawers.$bottom.trigger('transitionend');},400);if(drawers.$next){drawers.$next.css('top',this._isMainAppContent(drawers.$next)?drawerHeight:drawers.$next.offset().top-drawerHeight);}},_getDrawers:function(open){var $main=app.$contentEl.children().first(),$nextDrawer,$topDrawer,$bottomDrawer,open=_.isUndefined(open)?true:open,drawerCount=this._components.length;switch(drawerCount){case 0:break;case 1:$nextDrawer=open?this._components[drawerCount-1].$el:undefined;$topDrawer=open?$main:this._components[drawerCount-1].$el;$bottomDrawer=open?undefined:$main;break;case 2:$nextDrawer=open?this._components[drawerCount-1].$el:$main;$topDrawer=open?this._components[drawerCount-2].$el:this._components[drawerCount-1].$el;$bottomDrawer=open?$main:this._components[drawerCount-2].$el;break;default:$nextDrawer=open?this._components[drawerCount-1].$el:this._components[drawerCount-3].$el;$topDrawer=open?this._components[drawerCount-2].$el:this._components[drawerCount-1].$el;$bottomDrawer=open?this._components[drawerCount-3].$el:this._components[drawerCount-2].$el;}
return{$next:$nextDrawer,$top:$topDrawer,$bottom:$bottomDrawer};},_isMainAppContent:function($layout){return!$layout.parent().is(this.$el);},_determineDrawerHeight:function(){var windowHeight=$(window).height(),headerHeight=$('#header .navbar').outerHeight(),footerHeight=$('footer').outerHeight();return windowHeight-headerHeight-footerHeight-this.pixelsFromFooter;},_determineCollapsedHeight:function(){return $(window).height()/2;},_createTabAndBackdrop:function($top,$bottom){var $drawerTab;this.expandTpl=app.template.getLayout(this.name+'.expand');this.expandTabHtml=this.expandTpl();$bottom.append(this.expandTabHtml).append(this.backdropHtml);$drawerTab=$bottom.find('.drawer-tab');this.addPluginTooltips($drawerTab);$drawerTab.on('click',_.bind(function(event){if($('i',event.currentTarget).hasClass('icon-chevron-up')){this._collapseDrawer($top,$bottom);}else{this._expandDrawer($top,$bottom);}
return false;},this));},_removeTabAndBackdrop:function($drawer){var $drawerTab=$drawer.find('.drawer-tab').off('click').remove();this.removePluginTooltips($drawerTab);$drawer.find('.drawer-backdrop').remove();},_cleanUpAfterClose:function(drawers){this._removeTabAndBackdrop(drawers.$bottom);if(this._isMainAppContent(drawers.$bottom)){drawers.$bottom.removeClass('drawer transition active');$('body').removeClass('noscroll');app.$contentEl.removeClass('noscroll');}else{this._expandDrawer(drawers.$bottom,drawers.$next);}
if(this._components.length===1){$(window).off('resize.drawer');}},_expandDrawer:function($top,$bottom){var expandHeight=this._determineDrawerHeight();$top.css('height',expandHeight);if($bottom.closest('#drawers').length>0){$bottom.css('top',expandHeight+$top.offset().top);}else{$bottom.css('top',expandHeight);}
$bottom.find('.drawer-tab i').removeClass('icon-chevron-down').addClass('icon-chevron-up');this.trigger('drawer:resize',expandHeight);},_collapseDrawer:function($top,$bottom){var collapseHeight=this._determineCollapsedHeight();$top.css('height',collapseHeight);if($bottom.closest('#drawers').length>0){$bottom.css('top',collapseHeight+$top.offset().top);}else{$bottom.css('top',collapseHeight);}
$bottom.find('.drawer-tab i').removeClass('icon-chevron-up').addClass('icon-chevron-down');this.trigger('drawer:resize',collapseHeight);},_scrollToTop:function(){var drawers=this._getDrawers(true),$mainpane=drawers.$top.find('.main-pane'),$sidepane=drawers.$top.find('.sidebar-content');this.scrollTopPositions.push({main:$mainpane.scrollTop(),side:$sidepane.scrollTop()});$mainpane.scrollTop(0);$sidepane.scrollTop(0);},_scrollBackToOriginal:function(drawerLayout){var scrollPositions=this.scrollTopPositions.pop();if(drawerLayout){drawerLayout.$('.main-pane').scrollTop(scrollPositions.main);drawerLayout.$('.sidebar-content').scrollTop(scrollPositions.side);}else{app.$contentEl.find('.main-pane').scrollTop(scrollPositions.main);app.$contentEl.find('.sidebar-content').scrollTop(scrollPositions.side);}},getHeight:function(){if(_.isEmpty(this._components)){return 0;}
var $top=this._getDrawers(false).$top;return $top.height();},_dispose:function(){app.routing.offBefore("route",this.reset,this);this.reset();$(window).off('resize.drawer');app.view.View.prototype._dispose.call(this);},_resizeDrawer:_.throttle(function(){var drawers=this._getDrawers(false);if(drawers.$top){this._expandDrawer(drawers.$top,drawers.$bottom);}},300)})