<?PHP
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN rt_companies
 */

require_once('include/SugarObjects/templates/company/Company.php');

class rt_companies_sugar extends Company {
	var $new_schema = true;
	var $module_dir = 'rt_companies';
	var $object_name = 'rt_companies';
	var $table_name = 'rt_companies';
	var $importable = false;
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $activities;
		var $team_id;
		var $team_set_id;
		var $team_count;
		var $team_name;
		var $team_link;
		var $team_count_link;
		var $teams;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $linkedin;
		var $facebook;
		var $twitter;
		var $googleplus;
		var $rt_companies_type;
		var $industry;
		var $annual_revenue;
		var $phone_fax;
		var $billing_address_street;
		var $billing_address_street_2;
		var $billing_address_street_3;
		var $billing_address_street_4;
		var $billing_address_city;
		var $billing_address_state;
		var $billing_address_postalcode;
		var $billing_address_country;
		var $rating;
		var $phone_office;
		var $phone_alternate;
		var $website;
		var $ownership;
		var $employees;
		var $ticker_symbol;
		var $shipping_address_street;
		var $shipping_address_street_2;
		var $shipping_address_street_3;
		var $shipping_address_street_4;
		var $shipping_address_city;
		var $shipping_address_state;
		var $shipping_address_postalcode;
		var $shipping_address_country;
		var $email;
		var $email1;
		var $email_addresses_primary;
		var $email_addresses;
		
	/**
	 * This is a depreciated method, please start using __construct() as this method will be removed in a future version
     *
     * @see __construct
     * @depreciated
	 */
	function rt_companies_sugar(){
		self::__construct();
	}

	public function __construct(){
		parent::__construct();
	}
	
	public function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>