/*********************************************************************************
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
     ********************************************************************************/
({plugins:['Dashlet','EllipsisInline'],likelyTotal:0,bestTotal:0,worstTotal:0,shouldRollup:false,selectedUser:{},isForecastSetup:false,isForecastAdmin:false,subDetailsTpl:{},detailsMsgTpl:{},detailsDataSet:{},forecastConfig:{},showTimeperiod:true,forecastsConfigOK:false,serverData:{},currentModule:'',spanCSS:'',initDataLoaded:false,events:{'click #forecastsProgressDisplayOptions div.datasetOptions label.radio':'changeDisplayOptions'},oldTotals:{},quotaCollection:undefined,noDataAccessTemplate:undefined,fieldDataAccess:{},initialize:function(options){app.view.View.prototype.initialize.call(this,options);this.currentModule=app.controller.context.get("module");this.forecastConfig=app.metadata.getModule('Forecasts','config');this.isForecastSetup=this.forecastConfig.is_setup;this.forecastsConfigOK=app.utils.checkForecastConfig();if(this.isForecastSetup&&this.forecastsConfigOK){this.serverData=new Backbone.Model();var aclModule=this.forecastConfig.forecast_by,likelyFieldName=(aclModule=='RevenueLineItems')?'likely_case':'amount';this.fieldDataAccess={likely:app.acl.hasAccess('read',aclModule,app.user.get('id'),likelyFieldName),best:app.acl.hasAccess('read',aclModule,app.user.get('id'),'best_case'),worst:app.acl.hasAccess('read',aclModule,app.user.get('id'),'worst_case')};var hasAccess=(this.fieldDataAccess.likely&&this.fieldDataAccess.best&&this.fieldDataAccess.worst);if(hasAccess===false){this.noDataAccessTemplate=app.template.getField('base','noaccess')(this);}
this.resetModel();this.context.get('model').module='Forecasts';this.selectedUser=app.user.toJSON();if(this.currentModule!='Home'){this.shouldRollup=this.isManagerView();}else{this.shouldRollup=this.selectedUser.is_manager;}
this.isForecastAdmin=_.isUndefined(app.user.getAcls()['Forecasts'].admin);this.subDetailsTpl=app.template.getView('forecastdetails.sub-details');this.detailsMsgTpl=app.template.getView('forecastdetails.details-msg');this.detailsDataSet=this.setUpShowDetailsDataSet(this.forecastConfig);this.checkSpanCSS();}},checkSpanCSS:function(){var ct=0;_.each([this.forecastConfig.show_worksheet_likely,this.forecastConfig.show_worksheet_best,this.forecastConfig.show_worksheet_worst],function(val)
{if(val){ct++;}});switch(ct){case 3:this.spanCSS='4';break;case 2:this.spanCSS='6';break;case 1:this.spanCSS='12';break;case 0:this.spanCSS='';break;}
this.model.set({spanCSS:this.spanCSS},{silent:true});},setUpShowDetailsDataSet:function(cfg){var ds=app.metadata.getStrings('app_list_strings')['forecasts_options_dataset']||[];var returnDs={};_.each(ds,function(value,key){if(cfg['show_worksheet_'+key]==1){returnDs[key]=value}},this);return returnDs;},resetModel:function(){var model={opportunities:0,closed_amount:undefined,quota_amount:undefined,deficit_amount:undefined,worst_details:undefined,likely_details:undefined,best_details:undefined,show_details_likely:this.forecastConfig.show_worksheet_likely,show_details_best:this.forecastConfig.show_worksheet_best,show_details_worst:this.forecastConfig.show_worksheet_worst,spanCSS:this.spanCSS,quota_amount_str:undefined,closed_amount_str:undefined,deficit_class:undefined,deficit_amount_str:undefined,isForecastSetup:this.isForecastSetup,isForecastAdmin:this.isForecastAdmin};if(this.context.get('model')){this.context.get('model').set(model)}else{this.model.set(model);}},getProjectedURL:function(){var method=this.shouldRollup?"progressManager":"progressRep",url='Forecasts/'+this.model.get('selectedTimePeriod')+'/'+method+'/'+this.selectedUser.id;return app.api.buildURL(url,'create');},bindDataChange:function(){if(this.meta.config){return;}
var ctx=this.model;if(this.currentModule=='Forecasts'){ctx=this.context.parent||this.context;this.showTimeperiod=false;}
ctx.on('change:selectedTimePeriod',function(model){if(this.currentModule=='Forecasts'){this.updateDetailsForSelectedTimePeriod(model.get('selectedTimePeriod'));}
this.loadData({});},this);if(this.currentModule=='Forecasts'){this.quotaCollection=app.utils.getSubpanelCollection(ctx,'ForecastManagerWorksheets');this.quotaCollection.on('reset',this.processQuotaCollection,this);this.quotaCollection.on('change:quota',function(data){var oldQuota=(this.getOldTotalFromCollectionById(data.get('id')))?this.getOldTotalFromCollectionById(data.get('id')).quota:0,newQuota=data.get('quota'),diff=app.math.sub(data.get('quota'),oldQuota),newQuotaTotal=app.math.add(this.serverData.get('quota_amount'),diff);this.setOldTotalFromCollectionById(data.get('id'),{quota:newQuota});this.calculateData({quota_amount:newQuotaTotal});},this);this.processQuotaCollection();ctx.on('change:selectedUser',function(model){this.updateDetailsForSelectedUser(model.get('selectedUser'));this.loadData({});},this);ctx.on('forecasts:worksheet:totals',function(data){this.calculateData(this.mapAllTheThings(data,true),true);},this);if(!_.has(ctx.attributes,'lhsData')){ctx.set({lhsData:{quotas:this.oldTotals}});}}},unbindData:function(){var ctx;if(this.currentModule&&this.currentModule=='Forecasts'){ctx=this.context.parent||this.context;}else{ctx=this.model;}
if(ctx){ctx.off(null,null,this);}
if(this.currentModule=='Forecasts'&&this.quotaCollection){this.quotaCollection.off();}
app.view.View.prototype.unbindData.call(this);},loadData:function(options){if(this.meta.config){return;}
if(!this.initDataLoaded){this.getInitData(options);}
if(!_.isEmpty(this.model.get('selectedTimePeriod'))){var url=this.getProjectedURL(),cb={context:this,success:this.handleNewDataFromServer,complete:options?options.complete:null};app.api.call('read',url,null,null,cb);}},getInitData:function(options){app.api.call('GET',app.api.buildURL('TimePeriods/current'),null,{success:_.bind(function(o){if(this.model){this.initDataLoaded=true;this.model.set({selectedTimePeriod:o.id},{silent:true});this.loadData();}},this),complete:options?options.complete:null});},processQuotaCollection:function(){var model=this.context.get('model')||this.model,newQuota=0,oldQuota=model.get('quota_amount'),quota=0;this.oldTotals.models=new Backbone.Model();_.each(this.quotaCollection.models,function(model){quota=model.get('quota');newQuota=app.math.add(newQuota,quota);this.setOldTotalFromCollectionById(model.get('id'),{quota:quota});},this);if(oldQuota!==newQuota){this.calculateData({quota_amount:newQuota});}},getOldTotalFromCollectionById:function(id){return this.oldTotals.models.get(id);},setOldTotalFromCollectionById:function(id,totals){this.oldTotals.models.set(id,totals);},_render:function(){app.view.View.prototype._render.call(this);this.renderSubDetails();},renderSubDetails:function(){if(this.$el&&this.subDetailsTpl){var subEl=this.$el.find('.forecast-details'),model=this.context.get('model')||this.model;if(!_.isUndefined(model.get('closed_amount'))&&!_.isUndefined(model.get('quota_amount'))){subEl.html(this.subDetailsTpl(model.toJSON()));this.renderCSSChanges(model);}else{subEl.html('');}}},renderCSSChanges:function(model){model=model||this.context.get('model')||this.model;var isDeficit=model.get('is_deficit');if(isDeficit){this.$el.find('.deficitRow').addClass(this.getClassBasedOnAmount(0,1,'color'));}else{this.$el.find('.deficitRow').addClass(this.getClassBasedOnAmount(1,0,'color'));}
this.checkPropertySetCSS('worst',model);this.checkPropertySetCSS('likely',model);this.checkPropertySetCSS('best',model);},checkPropertySetCSS:function(prop,model){model=model||this.context.get('model')||this.model;if(this.forecastConfig['show_worksheet_'+prop]&&(this.shouldRollup||(!this.shouldRollup&&this.fieldDataAccess[prop]))){var css=this.getClassBasedOnAmount(app.math.add(this.serverData.get(prop),this.serverData.get('closed_amount')),model.get('quota_amount'),'background-color');this.$el.find('#forecast_details_'+prop+'_feedback').addClass(css);}},mapAllTheThings:function(data,fromModel){if(this.shouldRollup){data.likely=data.likely_adjusted;data.best=data.best_adjusted;data.worst=data.worst_adjusted;}else{if(fromModel){data.likely=data.likely_case;}else{data.likely=data.amount;}
data.best=data.best_case;data.worst=data.worst_case;data.closed_amount=data.won_amount;if(_.isUndefined(data.closed_amount)){delete data.closed_amount;}}
if(fromModel){data.worst=app.math.sub(data.worst,(data.closed_amount||0));data.likely=app.math.sub(data.likely,(data.closed_amount||0));data.best=app.math.sub(data.best,(data.closed_amount||0));}
return data;},handleNewDataFromServer:function(data){if(this.currentModule=='Forecasts'&&this.context&&this.shouldRollup){var lhsData=this.context.get('lhsData');if(!lhsData&&_.has(this.context,'parent')&&!_.isNull(this.context.parent)){lhsData=this.context.parent.get('lhsData');}
if(lhsData&&!_.isEmpty(lhsData.quotas.models.attributes)){var lhsTotal=0;_.each(lhsData.quotas.models.attributes,function(val,key){lhsTotal=app.math.add(lhsTotal,val.quota);},this);if(lhsTotal!=parseFloat(data.quota_amount)){data.quota_amount=app.math.sub(data.quota_amount,app.math.sub(data.quota_amount,lhsTotal));}}}
this.calculateData(this.mapAllTheThings(data,false));},calculateData:function(data,fromModel){fromModel=fromModel||false;this.serverData.set(data);var d=_.extend({},data,this.serverData.toJSON());this.likelyTotal=d.likely;this.bestTotal=d.best;this.worstTotal=d.worst;d.quota_amount_str=app.currency.formatAmountLocale(d.quota_amount);d.closed_amount_str=app.currency.formatAmountLocale(d.closed_amount);d.deficit_amount=Math.abs(app.math.sub(d.quota_amount,d.closed_amount));d.deficit_amount_str=app.currency.formatAmountLocale(d.deficit_amount);d.is_deficit=(parseFloat(d.quota_amount)>parseFloat(d.closed_amount));var deficitLabelKey=(d.is_deficit)?'LBL_FORECAST_DETAILS_DEFICIT':'LBL_FORECAST_DETAILS_SURPLUS';d.deficit_label=app.lang.get(deficitLabelKey,'Forecasts');d.worst_details=this.detailsMsgTpl(this.getDetailsForCase('worst',this.worstTotal,d.quota_amount,d.closed_amount,fromModel));d.likely_details=this.detailsMsgTpl(this.getDetailsForCase('likely',this.likelyTotal,d.quota_amount,d.closed_amount,fromModel));d.best_details=this.detailsMsgTpl(this.getDetailsForCase('best',this.bestTotal,d.quota_amount,d.closed_amount,fromModel));if(this.shouldRollup){d.quota_label=app.lang.get('LBL_QUOTA_ADJUSTED','Forecasts');}else{d.quota_label=app.lang.get('LBL_QUOTA','Forecasts');}
if(this.context||this.model){var model=this.context.get('model')||this.model;if(model){model.set(d);this.renderSubDetails();}}},getDetailsForCase:function(caseStr,caseValue,stageValue,closedAmt,fromModel){var params={},caseValueN=app.math.add(caseValue,closedAmt),stageValueN=parseFloat(stageValue),openPipeline=0,calcValue=0;params.label=app.lang.get('LBL_'+caseStr.toUpperCase(),'Forecasts');params.spanCSS=this.spanCSS;params.case=caseStr;params.shortOrExceed='&nbsp;';params.openPipeline='&nbsp;';params.feedbackLn1='';params.feedbackLn2='';var hasAccess=true;if(!this.shouldRollup&&!this.fieldDataAccess[caseStr]){hasAccess=false;}
if(hasAccess)
{params.amount=app.currency.formatAmountLocale(caseValue);params.labelAmount=params.label+': '+params.amount.toString();if(caseValueN==0&&stageValueN==0){params.amount=app.lang.get('LBL_FORECAST_DETAILS_NO_DATA',"Forecasts");}else if(caseValueN!=0&&stageValueN!=0&&caseValueN==stageValueN){params.shortOrExceed=app.lang.get('LBL_FORECAST_DETAILS_MEETING_QUOTA',"Forecasts");}else{if(caseValueN>stageValueN){params.shortOrExceed=app.lang.get('LBL_FORECAST_DETAILS_EXCEED',"Forecasts");calcValue=app.math.sub(caseValueN,stageValueN);}else{params.shortOrExceed=app.lang.get('LBL_FORECAST_DETAILS_SHORT',"Forecasts");calcValue=app.math.sub(stageValueN,caseValueN);}
params.percent=this.getPercent(calcValue,stageValueN);params.openPipeline='('+app.currency.formatAmountLocale(calcValue)+')';}
params.feedbackLn1=params.shortOrExceed;if(params.percent){params.feedbackLn1+=' '+params.percent;}
params.feedbackLn2=params.openPipeline;}else{params.amount=this.noDataAccessTemplate;params.labelAmount=params.label+': '+app.lang.get('LBL_NO_FIELD_ACCESS');}
return params;},getAbsDifference:function(caseValue,stageValue){return app.currency.formatAmountLocale(Math.abs(stageValue-caseValue));},getClassBasedOnAmount:function(caseValue,stageValue,type){var cssClass='';caseValue=parseFloat(caseValue);stageValue=parseFloat(stageValue);if(type=='color'){if(caseValue==stageValue){}else if(caseValue>stageValue){cssClass='font-green';}else{cssClass='font-red'}}else if(type=='background-color'){if(caseValue==stageValue){cssClass='grayLight';}else if(caseValue>stageValue){cssClass='green';}else{cssClass='red';}}
return cssClass;},getPercent:function(caseValue,stageValue){var percent=0,calcValue=caseValue;if(stageValue>0&&caseValue>0){percent=(calcValue / stageValue)*100;if(percent>1){percent=Math.round(percent);}else{percent=Math.round(percent*100)/100;}}
return Math.abs(percent)+'%';},isManagerView:function(){var isMgrView=false;if(this.currentModule=='Forecasts'&&this.selectedUser.isManager==true&&(this.selectedUser.showOpps==undefined||this.selectedUser.showOpps===false))
{isMgrView=true;}
return isMgrView;},updateDetailsForSelectedTimePeriod:function(timePeriod){this.model.set({selectedTimePeriod:timePeriod});},updateDetailsForSelectedUser:function(selectedUser){this.selectedUser.last_name=selectedUser.last_name;this.selectedUser.first_name=selectedUser.first_name;this.selectedUser.full_name=selectedUser.full_name;this.selectedUser.id=selectedUser.id;this.selectedUser.isManager=selectedUser.isManager;this.selectedUser.reportees=selectedUser.reportees;this.selectedUser.showOpps=selectedUser.showOpps;this.selectedUser.user_name=selectedUser.user_name;this.shouldRollup=this.isManagerView();this.model.set({selectedUser:selectedUser});},changeDisplayOptions:function(evt){evt.preventDefault();this.handleOptionChange(evt);},handleOptionChange:function(evt){var $el=$(evt.currentTarget),changedSegment=$el.attr('data-set');if($el.hasClass('checked')){$el.removeClass('checked');$('div .projected_'+changedSegment).hide();}else{$el.addClass('checked');$('div .projected_'+changedSegment).show();}}})